/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: tendermint/crypto/proof.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "tendermint/crypto/proof.pb-c.h"
void   tendermint__crypto__proof__init
                     (Tendermint__Crypto__Proof         *message)
{
  static const Tendermint__Crypto__Proof init_value = TENDERMINT__CRYPTO__PROOF__INIT;
  *message = init_value;
}
size_t tendermint__crypto__proof__get_packed_size
                     (const Tendermint__Crypto__Proof *message)
{
  assert(message->base.descriptor == &tendermint__crypto__proof__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tendermint__crypto__proof__pack
                     (const Tendermint__Crypto__Proof *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tendermint__crypto__proof__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tendermint__crypto__proof__pack_to_buffer
                     (const Tendermint__Crypto__Proof *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tendermint__crypto__proof__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Tendermint__Crypto__Proof *
       tendermint__crypto__proof__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Tendermint__Crypto__Proof *)
     protobuf_c_message_unpack (&tendermint__crypto__proof__descriptor,
                                allocator, len, data);
}
void   tendermint__crypto__proof__free_unpacked
                     (Tendermint__Crypto__Proof *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &tendermint__crypto__proof__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tendermint__crypto__value_op__init
                     (Tendermint__Crypto__ValueOp         *message)
{
  static const Tendermint__Crypto__ValueOp init_value = TENDERMINT__CRYPTO__VALUE_OP__INIT;
  *message = init_value;
}
size_t tendermint__crypto__value_op__get_packed_size
                     (const Tendermint__Crypto__ValueOp *message)
{
  assert(message->base.descriptor == &tendermint__crypto__value_op__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tendermint__crypto__value_op__pack
                     (const Tendermint__Crypto__ValueOp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tendermint__crypto__value_op__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tendermint__crypto__value_op__pack_to_buffer
                     (const Tendermint__Crypto__ValueOp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tendermint__crypto__value_op__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Tendermint__Crypto__ValueOp *
       tendermint__crypto__value_op__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Tendermint__Crypto__ValueOp *)
     protobuf_c_message_unpack (&tendermint__crypto__value_op__descriptor,
                                allocator, len, data);
}
void   tendermint__crypto__value_op__free_unpacked
                     (Tendermint__Crypto__ValueOp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &tendermint__crypto__value_op__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tendermint__crypto__domino_op__init
                     (Tendermint__Crypto__DominoOp         *message)
{
  static const Tendermint__Crypto__DominoOp init_value = TENDERMINT__CRYPTO__DOMINO_OP__INIT;
  *message = init_value;
}
size_t tendermint__crypto__domino_op__get_packed_size
                     (const Tendermint__Crypto__DominoOp *message)
{
  assert(message->base.descriptor == &tendermint__crypto__domino_op__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tendermint__crypto__domino_op__pack
                     (const Tendermint__Crypto__DominoOp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tendermint__crypto__domino_op__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tendermint__crypto__domino_op__pack_to_buffer
                     (const Tendermint__Crypto__DominoOp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tendermint__crypto__domino_op__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Tendermint__Crypto__DominoOp *
       tendermint__crypto__domino_op__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Tendermint__Crypto__DominoOp *)
     protobuf_c_message_unpack (&tendermint__crypto__domino_op__descriptor,
                                allocator, len, data);
}
void   tendermint__crypto__domino_op__free_unpacked
                     (Tendermint__Crypto__DominoOp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &tendermint__crypto__domino_op__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tendermint__crypto__proof_op__init
                     (Tendermint__Crypto__ProofOp         *message)
{
  static const Tendermint__Crypto__ProofOp init_value = TENDERMINT__CRYPTO__PROOF_OP__INIT;
  *message = init_value;
}
size_t tendermint__crypto__proof_op__get_packed_size
                     (const Tendermint__Crypto__ProofOp *message)
{
  assert(message->base.descriptor == &tendermint__crypto__proof_op__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tendermint__crypto__proof_op__pack
                     (const Tendermint__Crypto__ProofOp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tendermint__crypto__proof_op__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tendermint__crypto__proof_op__pack_to_buffer
                     (const Tendermint__Crypto__ProofOp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tendermint__crypto__proof_op__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Tendermint__Crypto__ProofOp *
       tendermint__crypto__proof_op__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Tendermint__Crypto__ProofOp *)
     protobuf_c_message_unpack (&tendermint__crypto__proof_op__descriptor,
                                allocator, len, data);
}
void   tendermint__crypto__proof_op__free_unpacked
                     (Tendermint__Crypto__ProofOp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &tendermint__crypto__proof_op__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tendermint__crypto__proof_ops__init
                     (Tendermint__Crypto__ProofOps         *message)
{
  static const Tendermint__Crypto__ProofOps init_value = TENDERMINT__CRYPTO__PROOF_OPS__INIT;
  *message = init_value;
}
size_t tendermint__crypto__proof_ops__get_packed_size
                     (const Tendermint__Crypto__ProofOps *message)
{
  assert(message->base.descriptor == &tendermint__crypto__proof_ops__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tendermint__crypto__proof_ops__pack
                     (const Tendermint__Crypto__ProofOps *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tendermint__crypto__proof_ops__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tendermint__crypto__proof_ops__pack_to_buffer
                     (const Tendermint__Crypto__ProofOps *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tendermint__crypto__proof_ops__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Tendermint__Crypto__ProofOps *
       tendermint__crypto__proof_ops__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Tendermint__Crypto__ProofOps *)
     protobuf_c_message_unpack (&tendermint__crypto__proof_ops__descriptor,
                                allocator, len, data);
}
void   tendermint__crypto__proof_ops__free_unpacked
                     (Tendermint__Crypto__ProofOps *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &tendermint__crypto__proof_ops__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor tendermint__crypto__proof__field_descriptors[4] =
{
  {
    "total",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Tendermint__Crypto__Proof, total),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "index",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Tendermint__Crypto__Proof, index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "leaf_hash",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Tendermint__Crypto__Proof, leaf_hash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "aunts",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Tendermint__Crypto__Proof, n_aunts),
    offsetof(Tendermint__Crypto__Proof, aunts),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tendermint__crypto__proof__field_indices_by_name[] = {
  3,   /* field[3] = aunts */
  1,   /* field[1] = index */
  2,   /* field[2] = leaf_hash */
  0,   /* field[0] = total */
};
static const ProtobufCIntRange tendermint__crypto__proof__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor tendermint__crypto__proof__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tendermint.crypto.Proof",
  "Proof",
  "Tendermint__Crypto__Proof",
  "tendermint.crypto",
  sizeof(Tendermint__Crypto__Proof),
  4,
  tendermint__crypto__proof__field_descriptors,
  tendermint__crypto__proof__field_indices_by_name,
  1,  tendermint__crypto__proof__number_ranges,
  (ProtobufCMessageInit) tendermint__crypto__proof__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tendermint__crypto__value_op__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Tendermint__Crypto__ValueOp, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "proof",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Tendermint__Crypto__ValueOp, proof),
    &tendermint__crypto__proof__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tendermint__crypto__value_op__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = proof */
};
static const ProtobufCIntRange tendermint__crypto__value_op__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor tendermint__crypto__value_op__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tendermint.crypto.ValueOp",
  "ValueOp",
  "Tendermint__Crypto__ValueOp",
  "tendermint.crypto",
  sizeof(Tendermint__Crypto__ValueOp),
  2,
  tendermint__crypto__value_op__field_descriptors,
  tendermint__crypto__value_op__field_indices_by_name,
  1,  tendermint__crypto__value_op__number_ranges,
  (ProtobufCMessageInit) tendermint__crypto__value_op__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tendermint__crypto__domino_op__field_descriptors[3] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Tendermint__Crypto__DominoOp, key),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "input",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Tendermint__Crypto__DominoOp, input),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "output",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Tendermint__Crypto__DominoOp, output),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tendermint__crypto__domino_op__field_indices_by_name[] = {
  1,   /* field[1] = input */
  0,   /* field[0] = key */
  2,   /* field[2] = output */
};
static const ProtobufCIntRange tendermint__crypto__domino_op__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor tendermint__crypto__domino_op__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tendermint.crypto.DominoOp",
  "DominoOp",
  "Tendermint__Crypto__DominoOp",
  "tendermint.crypto",
  sizeof(Tendermint__Crypto__DominoOp),
  3,
  tendermint__crypto__domino_op__field_descriptors,
  tendermint__crypto__domino_op__field_indices_by_name,
  1,  tendermint__crypto__domino_op__number_ranges,
  (ProtobufCMessageInit) tendermint__crypto__domino_op__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tendermint__crypto__proof_op__field_descriptors[3] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Tendermint__Crypto__ProofOp, type),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "key",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Tendermint__Crypto__ProofOp, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Tendermint__Crypto__ProofOp, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tendermint__crypto__proof_op__field_indices_by_name[] = {
  2,   /* field[2] = data */
  1,   /* field[1] = key */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange tendermint__crypto__proof_op__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor tendermint__crypto__proof_op__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tendermint.crypto.ProofOp",
  "ProofOp",
  "Tendermint__Crypto__ProofOp",
  "tendermint.crypto",
  sizeof(Tendermint__Crypto__ProofOp),
  3,
  tendermint__crypto__proof_op__field_descriptors,
  tendermint__crypto__proof_op__field_indices_by_name,
  1,  tendermint__crypto__proof_op__number_ranges,
  (ProtobufCMessageInit) tendermint__crypto__proof_op__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tendermint__crypto__proof_ops__field_descriptors[1] =
{
  {
    "ops",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Tendermint__Crypto__ProofOps, n_ops),
    offsetof(Tendermint__Crypto__ProofOps, ops),
    &tendermint__crypto__proof_op__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tendermint__crypto__proof_ops__field_indices_by_name[] = {
  0,   /* field[0] = ops */
};
static const ProtobufCIntRange tendermint__crypto__proof_ops__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor tendermint__crypto__proof_ops__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "tendermint.crypto.ProofOps",
  "ProofOps",
  "Tendermint__Crypto__ProofOps",
  "tendermint.crypto",
  sizeof(Tendermint__Crypto__ProofOps),
  1,
  tendermint__crypto__proof_ops__field_descriptors,
  tendermint__crypto__proof_ops__field_indices_by_name,
  1,  tendermint__crypto__proof_ops__number_ranges,
  (ProtobufCMessageInit) tendermint__crypto__proof_ops__init,
  NULL,NULL,NULL    /* reserved[123] */
};
