

LV_ALIGN_CENTER = 0
LV_ALIGN_IN_TOP_LEFT=1
LV_ALIGN_IN_TOP_MID=2
LV_ALIGN_IN_TOP_RIGHT=3
LV_ALIGN_IN_BOTTOM_LEFT=4
LV_ALIGN_IN_BOTTOM_MID=5
LV_ALIGN_IN_BOTTOM_RIGHT=6
LV_ALIGN_IN_LEFT_MID=7
LV_ALIGN_IN_RIGHT_MID=8
LV_ALIGN_OUT_TOP_LEFT=9
LV_ALIGN_OUT_TOP_MID=10
LV_ALIGN_OUT_TOP_RIGHT=11
LV_ALIGN_OUT_BOTTOM_LEFT=12
LV_ALIGN_OUT_BOTTOM_MID=13
LV_ALIGN_OUT_BOTTOM_RIGHT=14
LV_ALIGN_OUT_LEFT_TOP=15
LV_ALIGN_OUT_LEFT_MID=16
LV_ALIGN_OUT_LEFT_BOTTOM=17
LV_ALIGN_OUT_RIGHT_TOP=18
LV_ALIGN_OUT_RIGHT_MID=19
LV_ALIGN_OUT_RIGHT_BOTTOM=20


LV_DISP_ROT_NONE = 0
LV_DISP_ROT_90=1
LV_DISP_ROT_180=2
LV_DISP_ROT_270=3

LV_DISP_SIZE_SMALL=0
LV_DISP_SIZE_MEDIUM=1
LV_DISP_SIZE_LARGE=2
LV_DISP_SIZE_EXTRA_LARGE=3

LV_DRAG_DIR_HOR = 0x1
LV_DRAG_DIR_VER = 0x2
LV_DRAG_DIR_BOTH = 0x3
LV_DRAG_DIR_ONE = 0x4

LV_GESTURE_DIR_TOP=0
LV_GESTURE_DIR_BOTTOM=1
LV_GESTURE_DIR_LEFT=2
LV_GESTURE_DIR_RIGHT=3

LV_ANIM_OFF=0
LV_ANIM_ON=1

LV_BLEND_MODE_NORMAL=0
LV_BLEND_MODE_ADDITIVE=1
LV_BLEND_MODE_SUBTRACTIVE=2

// Obj parts
OBJ_PART_MAIN=0
OBJ_PART_VIRTUAL_FIRST=1
OBJ_PART_REAL_FIRST=0x40
OBJ_PART_ALL=0xFF
// LV State
STATE_DEFAULT=0x00
STATE_CHECKED=0x01
STATE_FOCUSED=0x02
STATE_EDITED=0x04
STATE_HOVERED=0x08
STATE_PRESSED=0x10
STATE_DISABLED=0x20
// OPA opacity
OPA_TRANSP=0
OPA_0=0
OPA_10=25
OPA_20=51
OPA_30=76
OPA_40=102
OPA_50=127
OPA_60=153
OPA_70=178
OPA_80=204
OPA_90=229
OPA_100=255
OPA_COVER=255
// LV Colors - we store in 24 bits format and will convert at runtime
WHITE=0xFFFFFF
SILVER=0xC0C0C0
GRAY=0x808080
BLACK=0x000000
RED=0xFF0000
MAROON=0x800000
YELLOW=0xFFFF00
OLIVE=0x808000
LIME=0x00FF00
GREEN=0x008000
CYAN=0x00FFFF
AQUA=0x00FFFF
TEAL=0x008080
BLUE=0x0000FF
NAVY=0x000080
MAGENTA=0xFF00FF
PURPLE=0x800080

// LV Groups
KEY_UP=17
KEY_DOWN=18
KEY_RIGHT=19
KEY_LEFT=20
KEY_ESC=27
KEY_DEL=127
KEY_BACKSPACE=8
KEY_ENTER=10
KEY_NEXT=9
KEY_PREV=11
KEY_HOME=2
KEY_END=3

// LV Style
BORDER_SIDE_NONE=0
BORDER_SIDE_BOTTOM=1
BORDER_SIDE_TOP=2
BORDER_SIDE_LEFT=4
BORDER_SIDE_RIGHT=8
BORDER_SIDE_FULL=15
BORDER_SIDE_INTERNAL=16

GRAD_DIR_NONE=0
GRAD_DIR_VER=1
GRAD_DIR_HOR=2

LV_TEXT_DECOR_NONE = 0x00
LV_TEXT_DECOR_UNDERLINE = 0x01
LV_TEXT_DECOR_STRIKETHROUGH = 0x02

// LV Styles parts

LV_STYLE_RADIUS = (((0x0 << 4) + 0x0 + 1) | ((0) << 8))
LV_STYLE_CLIP_CORNER = (((0x0 << 4) + 0x0 + 2) | ((0) << 8))
LV_STYLE_SIZE = (((0x0 << 4) + 0x0 + 3) | ((0) << 8))
LV_STYLE_TRANSFORM_WIDTH = (((0x0 << 4) + 0x0 + 4) | ((0) << 8))
LV_STYLE_TRANSFORM_HEIGHT = (((0x0 << 4) + 0x0 + 5) | ((0) << 8))
LV_STYLE_TRANSFORM_ANGLE = (((0x0 << 4) + 0x0 + 6) | ((0) << 8))
LV_STYLE_TRANSFORM_ZOOM = (((0x0 << 4) + 0x0 + 7) | ((0) << 8))
LV_STYLE_OPA_SCALE = (((0x0 << 4) + 0xC + 0) | (((1 << 7)) << 8))

LV_STYLE_PAD_TOP = (((0x1 << 4) + 0x0 + 0) | ((0) << 8))
LV_STYLE_PAD_BOTTOM = (((0x1 << 4) + 0x0 + 1) | ((0) << 8))
LV_STYLE_PAD_LEFT = (((0x1 << 4) + 0x0 + 2) | ((0) << 8))
LV_STYLE_PAD_RIGHT = (((0x1 << 4) + 0x0 + 3) | ((0) << 8))
LV_STYLE_PAD_INNER = (((0x1 << 4) + 0x0 + 4) | ((0) << 8))
LV_STYLE_MARGIN_TOP = (((0x1 << 4) + 0x0 + 5) | ((0) << 8))
LV_STYLE_MARGIN_BOTTOM = (((0x1 << 4) + 0x0 + 6) | ((0) << 8))
LV_STYLE_MARGIN_LEFT = (((0x1 << 4) + 0x0 + 7) | ((0) << 8))
LV_STYLE_MARGIN_RIGHT = (((0x1 << 4) + 0x0 + 8) | ((0) << 8))

LV_STYLE_BG_BLEND_MODE = (((0x2 << 4) + 0x0 + 0) | ((0) << 8))
LV_STYLE_BG_MAIN_STOP = (((0x2 << 4) + 0x0 + 1) | ((0) << 8))
LV_STYLE_BG_GRAD_STOP = (((0x2 << 4) + 0x0 + 2) | ((0) << 8))
LV_STYLE_BG_GRAD_DIR = (((0x2 << 4) + 0x0 + 3) | ((0) << 8))
LV_STYLE_BG_COLOR = (((0x2 << 4) + 0x9 + 0) | ((0) << 8))
LV_STYLE_BG_GRAD_COLOR = (((0x2 << 4) + 0x9 + 1) | ((0) << 8))
LV_STYLE_BG_OPA = (((0x2 << 4) + 0xC + 0) | ((0) << 8))

LV_STYLE_BORDER_WIDTH = (((0x3 << 4) + 0x0 + 0) | ((0) << 8))
LV_STYLE_BORDER_SIDE = (((0x3 << 4) + 0x0 + 1) | ((0) << 8))
LV_STYLE_BORDER_BLEND_MODE = (((0x3 << 4) + 0x0 + 2) | ((0) << 8))
LV_STYLE_BORDER_POST = (((0x3 << 4) + 0x0 + 3) | ((0) << 8))
LV_STYLE_BORDER_COLOR = (((0x3 << 4) + 0x9 + 0) | ((0) << 8))
LV_STYLE_BORDER_OPA = (((0x3 << 4) + 0xC + 0) | ((0) << 8))

LV_STYLE_OUTLINE_WIDTH = (((0x4 << 4) + 0x0 + 0) | ((0) << 8))
LV_STYLE_OUTLINE_PAD = (((0x4 << 4) + 0x0 + 1) | ((0) << 8))
LV_STYLE_OUTLINE_BLEND_MODE = (((0x4 << 4) + 0x0 + 2) | ((0) << 8))
LV_STYLE_OUTLINE_COLOR = (((0x4 << 4) + 0x9 + 0) | ((0) << 8))
LV_STYLE_OUTLINE_OPA = (((0x4 << 4) + 0xC + 0) | ((0) << 8))

LV_STYLE_SHADOW_WIDTH = (((0x5 << 4) + 0x0 + 0) | ((0) << 8))
LV_STYLE_SHADOW_OFS_X = (((0x5 << 4) + 0x0 + 1) | ((0) << 8))
LV_STYLE_SHADOW_OFS_Y = (((0x5 << 4) + 0x0 + 2) | ((0) << 8))
LV_STYLE_SHADOW_SPREAD = (((0x5 << 4) + 0x0 + 3) | ((0) << 8))
LV_STYLE_SHADOW_BLEND_MODE = (((0x5 << 4) + 0x0 + 4) | ((0) << 8))
LV_STYLE_SHADOW_COLOR = (((0x5 << 4) + 0x9 + 0) | ((0) << 8))
LV_STYLE_SHADOW_OPA = (((0x5 << 4) + 0xC + 0) | ((0) << 8))

LV_STYLE_PATTERN_BLEND_MODE = (((0x6 << 4) + 0x0 + 0) | ((0) << 8))
LV_STYLE_PATTERN_REPEAT = (((0x6 << 4) + 0x0 + 1) | ((0) << 8))
LV_STYLE_PATTERN_RECOLOR = (((0x6 << 4) + 0x9 + 0) | ((0) << 8))
LV_STYLE_PATTERN_OPA = (((0x6 << 4) + 0xC + 0) | ((0) << 8))
LV_STYLE_PATTERN_RECOLOR_OPA = (((0x6 << 4) + 0xC + 1) | ((0) << 8))
LV_STYLE_PATTERN_IMAGE = (((0x6 << 4) + 0xE + 0) | ((0) << 8))

LV_STYLE_VALUE_LETTER_SPACE = (((0x7 << 4) + 0x0 + 0) | ((0) << 8))
LV_STYLE_VALUE_LINE_SPACE = (((0x7 << 4) + 0x0 + 1) | ((0) << 8))
LV_STYLE_VALUE_BLEND_MODE = (((0x7 << 4) + 0x0 + 2) | ((0) << 8))
LV_STYLE_VALUE_OFS_X = (((0x7 << 4) + 0x0 + 3) | ((0) << 8))
LV_STYLE_VALUE_OFS_Y = (((0x7 << 4) + 0x0 + 4) | ((0) << 8))
LV_STYLE_VALUE_ALIGN = (((0x7 << 4) + 0x0 + 5) | ((0) << 8))
LV_STYLE_VALUE_COLOR = (((0x7 << 4) + 0x9 + 0) | ((0) << 8))
LV_STYLE_VALUE_OPA = (((0x7 << 4) + 0xC + 0) | ((0) << 8))
LV_STYLE_VALUE_FONT = (((0x7 << 4) + 0xE + 0) | ((0) << 8))
LV_STYLE_VALUE_STR = (((0x7 << 4) + 0xE + 1) | ((0) << 8))

LV_STYLE_TEXT_LETTER_SPACE = (((0x8 << 4) + 0x0 + 0) | (((1 << 7)) << 8))
LV_STYLE_TEXT_LINE_SPACE = (((0x8 << 4) + 0x0 + 1) | (((1 << 7)) << 8))
LV_STYLE_TEXT_DECOR = (((0x8 << 4) + 0x0 + 2) | (((1 << 7)) << 8))
LV_STYLE_TEXT_BLEND_MODE = (((0x8 << 4) + 0x0 + 3) | (((1 << 7)) << 8))
LV_STYLE_TEXT_COLOR = (((0x8 << 4) + 0x9 + 0) | (((1 << 7)) << 8))
LV_STYLE_TEXT_SEL_COLOR = (((0x8 << 4) + 0x9 + 1) | (((1 << 7)) << 8))
LV_STYLE_TEXT_SEL_BG_COLOR = (((0x8 << 4) + 0x9 + 2) | (((1 << 7)) << 8))
LV_STYLE_TEXT_OPA = (((0x8 << 4) + 0xC + 0) | (((1 << 7)) << 8))
LV_STYLE_TEXT_FONT = (((0x8 << 4) + 0xE + 0) | (((1 << 7)) << 8))

LV_STYLE_LINE_WIDTH = (((0x9 << 4) + 0x0 + 0) | ((0) << 8))
LV_STYLE_LINE_BLEND_MODE = (((0x9 << 4) + 0x0 + 1) | ((0) << 8))
LV_STYLE_LINE_DASH_WIDTH = (((0x9 << 4) + 0x0 + 2) | ((0) << 8))
LV_STYLE_LINE_DASH_GAP = (((0x9 << 4) + 0x0 + 3) | ((0) << 8))
LV_STYLE_LINE_ROUNDED = (((0x9 << 4) + 0x0 + 4) | ((0) << 8))
LV_STYLE_LINE_COLOR = (((0x9 << 4) + 0x9 + 0) | ((0) << 8))
LV_STYLE_LINE_OPA = (((0x9 << 4) + 0xC + 0) | ((0) << 8))

LV_STYLE_IMAGE_BLEND_MODE = (((0xA << 4) + 0x0 + 0) | (((1 << 7)) << 8))
LV_STYLE_IMAGE_RECOLOR = (((0xA << 4) + 0x9 + 0) | (((1 << 7)) << 8))
LV_STYLE_IMAGE_OPA = (((0xA << 4) + 0xC + 0) | (((1 << 7)) << 8))
LV_STYLE_IMAGE_RECOLOR_OPA = (((0xA << 4) + 0xC + 1) | (((1 << 7)) << 8))

LV_STYLE_TRANSITION_TIME = (((0xB << 4) + 0x0 + 0) | ((0) << 8))
LV_STYLE_TRANSITION_DELAY = (((0xB << 4) + 0x0 + 1) | ((0) << 8))
LV_STYLE_TRANSITION_PROP_1 = (((0xB << 4) + 0x0 + 2) | ((0) << 8))
LV_STYLE_TRANSITION_PROP_2 = (((0xB << 4) + 0x0 + 3) | ((0) << 8))
LV_STYLE_TRANSITION_PROP_3 = (((0xB << 4) + 0x0 + 4) | ((0) << 8))
LV_STYLE_TRANSITION_PROP_4 = (((0xB << 4) + 0x0 + 5) | ((0) << 8))
LV_STYLE_TRANSITION_PROP_5 = (((0xB << 4) + 0x0 + 6) | ((0) << 8))
LV_STYLE_TRANSITION_PROP_6 = (((0xB << 4) + 0x0 + 7) | ((0) << 8))
LV_STYLE_TRANSITION_PATH = (((0xB << 4) + 0xE + 0) | ((0) << 8))

LV_STYLE_SCALE_WIDTH = (((0xC << 4) + 0x0 + 0) | ((0) << 8))
LV_STYLE_SCALE_BORDER_WIDTH = (((0xC << 4) + 0x0 + 1) | ((0) << 8))
LV_STYLE_SCALE_END_BORDER_WIDTH = (((0xC << 4) + 0x0 + 2) | ((0) << 8))
LV_STYLE_SCALE_END_LINE_WIDTH = (((0xC << 4) + 0x0 + 3) | ((0) << 8))
LV_STYLE_SCALE_GRAD_COLOR = (((0xC << 4) + 0x9 + 0) | ((0) << 8))
LV_STYLE_SCALE_END_COLOR = (((0xC << 4) + 0x9 + 1) | ((0) << 8))

LV_TXT_FLAG_NONE = 0x00
LV_TXT_FLAG_RECOLOR = 0x01
LV_TXT_FLAG_EXPAND = 0x02
LV_TXT_FLAG_CENTER = 0x04
LV_TXT_FLAG_RIGHT = 0x08
LV_TXT_FLAG_FIT = 0x10

LV_TXT_CMD_STATE_WAIT=0
LV_TXT_CMD_STATE_PAR=1
LV_TXT_CMD_STATE_IN=2

LV_FS_RES_OK = 0
LV_FS_RES_HW_ERR=1
LV_FS_RES_FS_ERR=2
LV_FS_RES_NOT_EX=3
LV_FS_RES_FULL=4
LV_FS_RES_LOCKED=5
LV_FS_RES_DENIED=6
LV_FS_RES_BUSY=7
LV_FS_RES_TOUT=8
LV_FS_RES_NOT_IMP=9
LV_FS_RES_OUT_OF_MEM=10
LV_FS_RES_INV_PARAM=11
LV_FS_RES_UNKNOWN=12

LV_FS_MODE_WR = 0x01
LV_FS_MODE_RD = 0x02


LV_EVENT_PRESSED=0
LV_EVENT_PRESSING=1
LV_EVENT_PRESS_LOST=2
LV_EVENT_SHORT_CLICKED=3
LV_EVENT_LONG_PRESSED=4
LV_EVENT_LONG_PRESSED_REPEAT=5

LV_EVENT_CLICKED=6
LV_EVENT_RELEASED=7
LV_EVENT_DRAG_BEGIN=8
LV_EVENT_DRAG_END=9
LV_EVENT_DRAG_THROW_BEGIN=10
LV_EVENT_GESTURE=11
LV_EVENT_KEY=12
LV_EVENT_FOCUSED=13
LV_EVENT_DEFOCUSED=14
LV_EVENT_LEAVE=15
LV_EVENT_VALUE_CHANGED=16
LV_EVENT_INSERT=17
LV_EVENT_REFRESH=18
LV_EVENT_APPLY=19
LV_EVENT_CANCEL=20
LV_EVENT_DELETE=21


LV_PROTECT_NONE = 0x00
LV_PROTECT_CHILD_CHG = 0x01
LV_PROTECT_PARENT = 0x02
LV_PROTECT_POS = 0x04
LV_PROTECT_FOLLOW = 0x08

LV_PROTECT_PRESS_LOST = 0x10

LV_PROTECT_CLICK_FOCUS = 0x20
LV_PROTECT_EVENT_TO_DISABLED = 0x40

// LV Widgets
// LV Arc
ARC_TYPE_NORMAL=0
ARC_TYPE_SYMMETRIC=1
ARC_TYPE_REVERSE=2

ARC_PART_BG=0
ARC_PART_INDIC=1
ARC_PART_KNOB=2

// LV Bar
BAR_TYPE_NORMAL=0
BAR_TYPE_SYMMETRICAL=1
BAR_TYPE_CUSTOM=2

// Lv Btn
BTN_STATE_RELEASED=0
BTN_STATE_PRESSED=1
BTN_STATE_DISABLED=2
BTN_STATE_CHECKED_RELEASED=3
BTN_STATE_CHECKED_PRESSED=4
BTN_STATE_CHECKED_DISABLED=5

// Lv BtnMatrix
BTNMATRIX_CTRL_HIDDEN=0x0008
BTNMATRIX_CTRL_NO_REPEAT=0x0010
BTNMATRIX_CTRL_DISABLED=0x0020
BTNMATRIX_CTRL_CHECKABLE=0x0040
BTNMATRIX_CTRL_CHECK_STATE=0x0080
BTNMATRIX_CTRL_CLICK_TRIG=0x0100

// LV Calendar
CALENDAR_PART_BG=0
CALENDAR_PART_HEADER=1
CALENDAR_PART_DAY_NAMES=2
CALENDAR_PART_DATE=3

// LV Chart
CHART_TYPE_NONE=0
CHART_TYPE_LINE=1
CHART_TYPE_COLUMN=2

CHART_UPDATE_MODE_SHIFT=0
CHART_UPDATE_MODE_CIRCULAR=1

CHART_AXIS_PRIMARY_Y=0
CHART_AXIS_SECONDARY_Y=1

CHART_CURSOR_NONE=0
CHART_CURSOR_RIGHT=1
CHART_CURSOR_UP=2
CHART_CURSOR_LEFT=4
CHART_CURSOR_DOWN=8

CHART_AXIS_SKIP_LAST_TICK=0
CHART_AXIS_DRAW_LAST_TICK=1
CHART_AXIS_INVERSE_LABELS_ORDER=2

CHART_PART_BG=0
CHART_PART_SERIES_BG=1
CHART_PART_SERIES=2
CHART_PART_CURSOR=3

// LV Checkbox
CHECKBOX_PART_BG=0
CHECKBOX_PART_BULLET=0x40

// LV Cont
LAYOUT_OFF=0
LAYOUT_CENTER=1
LAYOUT_COLUMN_LEFT=2
LAYOUT_COLUMN_MID=3
LAYOUT_COLUMN_RIGHT=4
LAYOUT_ROW_TOP=5
LAYOUT_ROW_MID=6
LAYOUT_ROW_BOTTOM=7
LAYOUT_PRETTY_TOP=8
LAYOUT_PRETTY_MID=9
LAYOUT_PRETTY_BOTTOM=10
LAYOUT_GRID=11

FIT_NONE=0
FIT_TIGHT=1
FIT_PARENT=2
FIT_MAX=3

// LV Cpicker
CPICKER_TYPE_RECT=0
CPICKER_TYPE_DISC=1

CPICKER_COLOR_MODE_HUE=0
CPICKER_COLOR_MODE_SATURATION=1
CPICKER_COLOR_MODE_VALUE=2

CPICKER_PART_MAIN=0
CPICKER_PART_KNOB=1   // _LV_OBJ_PART_VIRTUAL_LAST

// LV Dropdown
DROPDOWN_DIR_DOWN=0
DROPDOWN_DIR_UP=1
DROPDOWN_DIR_LEFT=2
DROPDOWN_DIR_RIGHT=3

DROPDOWN_PART_MAIN=0
DROPDOWN_PART_LIST=0x40   // _LV_OBJ_PART_REAL_LAST
DROPDOWN_PART_SCROLLBAR=0x41
DROPDOWN_PART_SELECTED=0x42

// LV Gauge
GAUGE_PART_MAIN=0
GAUGE_PART_MAJOR=1
GAUGE_PART_NEEDLE=2

// LV Img
// LV Imgbtn

// LV Keyboard
KEYBOARD_MODE_TEXT_LOWER=0
KEYBOARD_MODE_TEXT_UPPER=1
KEYBOARD_MODE_SPECIAL=2
KEYBOARD_MODE_NUM=3

KEYBOARD_PART_BG=0
KEYBOARD_PART_BTN=1

// LV Label
LABEL_LONG_EXPAND=0
LABEL_LONG_BREAK=1
LABEL_LONG_DOT=2
LABEL_LONG_SROLL=3
LV_LABEL_LONG_SROLL_CIRC=4
LABEL_LONG_CROP=5

LABEL_ALIGN_LEFT=0
LABEL_ALIGN_CENTER=1
LABEL_ALIGN_RIGHT=2
LABEL_ALIGN_AUTO=3

// LV Led
LED_PART_MAIN=0

// LV Line
LINEMETER_PART_MAIN=0

// LV List
LIST_PART_BG=0
LIST_PART_SCROLLBAR=1
LIST_PART_EDGE_FLASH=2

// LV Msgbox
// enum {
//     LV_MSGBOX_PART_BG = LV_CONT_PART_MAIN,

//     LV_MSGBOX_PART_BTN_BG = _LV_CONT_PART_REAL_LAST,
//     LV_MSGBOX_PART_BTN,
// };

// LV Objmask
OBJMASK_PART_MAIN=0

// LV Templ
TEMPL_STYLE_X=0
TEMPL_STYLE_Y=1

// LV Page
SCROLLBAR_MODE_OFF=0
SCROLLBAR_MODE_ON=1
SCROLLBAR_MODE_DRAG=2
SCROLLBAR_MODE_AUTO=3
SCROLLBAR_MODE_HIDE=4
SCROLLBAR_MODE_UNHIDE=8

PAGE_EDGE_LEFT=1
PAGE_EDGE_TOP=2
PAGE_EDGE_RIGHT=4
PAGE_EDGE_BOTTOM=8
// enum {
//     LV_PAGE_PART_BG = LV_CONT_PART_MAIN,
//     LV_PAGE_PART_SCROLLBAR = _LV_OBJ_PART_VIRTUAL_LAST,
//     LV_PAGE_PART_EDGE_FLASH,
//     _LV_PAGE_PART_VIRTUAL_LAST,

//     LV_PAGE_PART_SCROLLABLE = _LV_OBJ_PART_REAL_LAST,
//     _LV_PAGE_PART_REAL_LAST,
// };

// LV Roller
ROLLER_MODE_NORMAL=0
ROLLER_MODE_INFINITE=1
// enum {
//     LV_ROLLER_PART_BG = LV_PAGE_PART_BG,
//     LV_ROLLER_PART_SELECTED = _LV_PAGE_PART_VIRTUAL_LAST,
//     _LV_ROLLER_PART_VIRTUAL_LAST,
// };

// LV Slider
SLIDER_TYPE_NORMAL=0
SLIDER_TYPE_SYMMETRICAL=1
SLIDER_TYPE_RANGE=2
// enum {
//     LV_SLIDER_PART_BG, /** Slider background style. */
//     LV_SLIDER_PART_INDIC, /** Slider indicator (filled area) style. */
//     LV_SLIDER_PART_KNOB, /** Slider knob style. */
// };

// LV Spinbox
// enum {
//     LV_SPINBOX_PART_BG = LV_TEXTAREA_PART_BG,
//     LV_SPINBOX_PART_CURSOR = LV_TEXTAREA_PART_CURSOR,
//     _LV_SPINBOX_PART_VIRTUAL_LAST = _LV_TEXTAREA_PART_VIRTUAL_LAST,
//     _LV_SPINBOX_PART_REAL_LAST = _LV_TEXTAREA_PART_REAL_LAST,
// };

// LV Spinner
SPINNER_TYPE_SPINNING_ARC=0
SPINNER_TYPE_FILLSPIN_ARC=1
SPINNER_TYPE_CONSTANT_ARC=2

SPINNER_DIR_FORWARD=0
SPINNER_DIR_BACKWARD=1
// enum {
//     LV_SPINNER_PART_BG = LV_ARC_PART_BG,
//     LV_SPINNER_PART_INDIC = LV_ARC_PART_INDIC,
//     _LV_SPINNER_PART_VIRTUAL_LAST,

//     _LV_SPINNER_PART_REAL_LAST = _LV_ARC_PART_REAL_LAST,
// };

// LV Switch
// enum {
//     LV_SWITCH_PART_BG = LV_BAR_PART_BG,                 /**< Switch background. */
//     LV_SWITCH_PART_INDIC = LV_BAR_PART_INDIC,           /**< Switch fill area. */
//     LV_SWITCH_PART_KNOB = _LV_BAR_PART_VIRTUAL_LAST,    /**< Switch knob. */
//     _LV_SWITCH_PART_VIRTUAL_LAST
// };

// LV Table
// enum {
//     LV_TABLE_PART_BG,     /* Because of this member, LV_PART.*CELL1 has enum value of 1,        */
//     LV_TABLE_PART_CELL1,  /*   LV_PART.*CELL2 has an enum value of 2 and so on up to the maximum */
//     LV_TABLE_PART_CELL2,  /*   number of styles specified by LV_TABLE_CELL_STYLE_CNT            */
//     LV_TABLE_PART_CELL3,
//     LV_TABLE_PART_CELL4,  /* CELL 5-16 are not needed to be defined, the values in this enum
//                              are there for backward compatibility */
// };

// LV Tabview
TABVIEW_TAB_POS_NONE=0
TABVIEW_TAB_POS_TOP=1
TABVIEW_TAB_POS_BOTTOM=2
TABVIEW_TAB_POS_LEFT=3
TABVIEW_TAB_POS_RIGHT=4
// enum {
//     LV_TABVIEW_PART_BG = LV_OBJ_PART_MAIN,
//     _LV_TABVIEW_PART_VIRTUAL_LAST = _LV_OBJ_PART_VIRTUAL_LAST,

//     LV_TABVIEW_PART_BG_SCROLLABLE = _LV_OBJ_PART_REAL_LAST,
//     LV_TABVIEW_PART_TAB_BG,
//     LV_TABVIEW_PART_TAB_BTN,
//     LV_TABVIEW_PART_INDIC,
//     _LV_TABVIEW_PART_REAL_LAST,
// };

// LV Textarea
TEXTAREA_CURSOR_LAST=0x7FFF
// enum {
//     LV_TEXTAREA_PART_BG = LV_PAGE_PART_BG, /**< Text area background style */
//     LV_TEXTAREA_PART_SCROLLBAR = LV_PAGE_PART_SCROLLBAR, /**< Scrollbar style */
//     LV_TEXTAREA_PART_EDGE_FLASH = LV_PAGE_PART_EDGE_FLASH, /**< Edge flash style */
//     LV_TEXTAREA_PART_CURSOR = _LV_PAGE_PART_VIRTUAL_LAST, /**< Cursor style */
//     LV_TEXTAREA_PART_PLACEHOLDER, /**< Placeholder style */
//     _LV_TEXTAREA_PART_VIRTUAL_LAST,

//     _LV_TEXTAREA_PART_REAL_LAST = _LV_PAGE_PART_REAL_LAST,
// };

// LV Tileview
// enum {
//     LV_TILEVIEW_PART_BG = LV_PAGE_PART_BG,
//     LV_TILEVIEW_PART_SCROLLBAR = LV_PAGE_PART_SCROLLBAR,
//     LV_TILEVIEW_PART_EDGE_FLASH = LV_PAGE_PART_EDGE_FLASH,
//     _LV_TILEVIEW_PART_VIRTUAL_LAST = _LV_PAGE_PART_VIRTUAL_LAST,
//     _LV_TILEVIEW_PART_REAL_LAST = _LV_PAGE_PART_REAL_LAST
// };

// LV Win
// enum {
//     LV_WIN_PART_BG = LV_OBJ_PART_MAIN, /**< Window object background style. */
//     _LV_WIN_PART_VIRTUAL_LAST,
//     LV_WIN_PART_HEADER = _LV_OBJ_PART_REAL_LAST, /**< Window titlebar background style. */
//     LV_WIN_PART_CONTENT_SCROLLABLE, /**< Window content style. */
//     LV_WIN_PART_SCROLLBAR, /**< Window scrollbar style. */
//     _LV_WIN_PART_REAL_LAST
// };


