COINES_INSTALL_PATH ?= ../../../..

EXAMPLE_FILE ?= forced_mode.c

API_LOCATION ?= ../..

C_SRCS += \
$(API_LOCATION)/bme68x.c \
../common/common.c

INCLUDEPATHS += \
$(API_LOCATION) \
../common

include $(COINES_INSTALL_PATH)/coines.mk