
/**
 * GENERATED FILE, DO NOT EDIT IT!
 * @file lv_style_properties.c
 */

#include "lv_style_properties.h"

#if LV_USE_OBJ_PROPERTY && LV_USE_OBJ_PROPERTY_NAME


/**
 * Style property names, name must be in order.
 * Generated code from properties.py
 */
/* *INDENT-OFF* */
const lv_property_name_t lv_style_property_names[112] = {
    {"align",                  LV_PROPERTY_STYLE_ALIGN,},
    {"anim",                   LV_PROPERTY_STYLE_ANIM,},
    {"anim_duration",          LV_PROPERTY_STYLE_ANIM_DURATION,},
    {"arc_color",              LV_PROPERTY_STYLE_ARC_COLOR,},
    {"arc_image_src",          LV_PROPERTY_STYLE_ARC_IMAGE_SRC,},
    {"arc_opa",                LV_PROPERTY_STYLE_ARC_OPA,},
    {"arc_rounded",            LV_PROPERTY_STYLE_ARC_ROUNDED,},
    {"arc_width",              LV_PROPERTY_STYLE_ARC_WIDTH,},
    {"base_dir",               LV_PROPERTY_STYLE_BASE_DIR,},
    {"bg_color",               LV_PROPERTY_STYLE_BG_COLOR,},
    {"bg_grad",                LV_PROPERTY_STYLE_BG_GRAD,},
    {"bg_grad_color",          LV_PROPERTY_STYLE_BG_GRAD_COLOR,},
    {"bg_grad_dir",            LV_PROPERTY_STYLE_BG_GRAD_DIR,},
    {"bg_grad_opa",            LV_PROPERTY_STYLE_BG_GRAD_OPA,},
    {"bg_grad_stop",           LV_PROPERTY_STYLE_BG_GRAD_STOP,},
    {"bg_image_opa",           LV_PROPERTY_STYLE_BG_IMAGE_OPA,},
    {"bg_image_recolor",       LV_PROPERTY_STYLE_BG_IMAGE_RECOLOR,},
    {"bg_image_recolor_opa",   LV_PROPERTY_STYLE_BG_IMAGE_RECOLOR_OPA,},
    {"bg_image_src",           LV_PROPERTY_STYLE_BG_IMAGE_SRC,},
    {"bg_image_tiled",         LV_PROPERTY_STYLE_BG_IMAGE_TILED,},
    {"bg_main_opa",            LV_PROPERTY_STYLE_BG_MAIN_OPA,},
    {"bg_main_stop",           LV_PROPERTY_STYLE_BG_MAIN_STOP,},
    {"bg_opa",                 LV_PROPERTY_STYLE_BG_OPA,},
    {"bitmap_mask_src",        LV_PROPERTY_STYLE_BITMAP_MASK_SRC,},
    {"blend_mode",             LV_PROPERTY_STYLE_BLEND_MODE,},
    {"border_color",           LV_PROPERTY_STYLE_BORDER_COLOR,},
    {"border_opa",             LV_PROPERTY_STYLE_BORDER_OPA,},
    {"border_post",            LV_PROPERTY_STYLE_BORDER_POST,},
    {"border_side",            LV_PROPERTY_STYLE_BORDER_SIDE,},
    {"border_width",           LV_PROPERTY_STYLE_BORDER_WIDTH,},
    {"clip_corner",            LV_PROPERTY_STYLE_CLIP_CORNER,},
    {"color_filter_dsc",       LV_PROPERTY_STYLE_COLOR_FILTER_DSC,},
    {"color_filter_opa",       LV_PROPERTY_STYLE_COLOR_FILTER_OPA,},
    {"flex_cross_place",       LV_PROPERTY_STYLE_FLEX_CROSS_PLACE,},
    {"flex_flow",              LV_PROPERTY_STYLE_FLEX_FLOW,},
    {"flex_grow",              LV_PROPERTY_STYLE_FLEX_GROW,},
    {"flex_main_place",        LV_PROPERTY_STYLE_FLEX_MAIN_PLACE,},
    {"flex_track_place",       LV_PROPERTY_STYLE_FLEX_TRACK_PLACE,},
    {"grid_cell_column_pos",   LV_PROPERTY_STYLE_GRID_CELL_COLUMN_POS,},
    {"grid_cell_column_span",  LV_PROPERTY_STYLE_GRID_CELL_COLUMN_SPAN,},
    {"grid_cell_row_pos",      LV_PROPERTY_STYLE_GRID_CELL_ROW_POS,},
    {"grid_cell_row_span",     LV_PROPERTY_STYLE_GRID_CELL_ROW_SPAN,},
    {"grid_cell_x_align",      LV_PROPERTY_STYLE_GRID_CELL_X_ALIGN,},
    {"grid_cell_y_align",      LV_PROPERTY_STYLE_GRID_CELL_Y_ALIGN,},
    {"grid_column_align",      LV_PROPERTY_STYLE_GRID_COLUMN_ALIGN,},
    {"grid_column_dsc_array",  LV_PROPERTY_STYLE_GRID_COLUMN_DSC_ARRAY,},
    {"grid_row_align",         LV_PROPERTY_STYLE_GRID_ROW_ALIGN,},
    {"grid_row_dsc_array",     LV_PROPERTY_STYLE_GRID_ROW_DSC_ARRAY,},
    {"height",                 LV_PROPERTY_STYLE_HEIGHT,},
    {"image_opa",              LV_PROPERTY_STYLE_IMAGE_OPA,},
    {"image_recolor",          LV_PROPERTY_STYLE_IMAGE_RECOLOR,},
    {"image_recolor_opa",      LV_PROPERTY_STYLE_IMAGE_RECOLOR_OPA,},
    {"last_built_in_prop",     LV_PROPERTY_STYLE_LAST_BUILT_IN_PROP,},
    {"layout",                 LV_PROPERTY_STYLE_LAYOUT,},
    {"length",                 LV_PROPERTY_STYLE_LENGTH,},
    {"line_color",             LV_PROPERTY_STYLE_LINE_COLOR,},
    {"line_dash_gap",          LV_PROPERTY_STYLE_LINE_DASH_GAP,},
    {"line_dash_width",        LV_PROPERTY_STYLE_LINE_DASH_WIDTH,},
    {"line_opa",               LV_PROPERTY_STYLE_LINE_OPA,},
    {"line_rounded",           LV_PROPERTY_STYLE_LINE_ROUNDED,},
    {"line_width",             LV_PROPERTY_STYLE_LINE_WIDTH,},
    {"margin_bottom",          LV_PROPERTY_STYLE_MARGIN_BOTTOM,},
    {"margin_left",            LV_PROPERTY_STYLE_MARGIN_LEFT,},
    {"margin_right",           LV_PROPERTY_STYLE_MARGIN_RIGHT,},
    {"margin_top",             LV_PROPERTY_STYLE_MARGIN_TOP,},
    {"max_height",             LV_PROPERTY_STYLE_MAX_HEIGHT,},
    {"max_width",              LV_PROPERTY_STYLE_MAX_WIDTH,},
    {"min_height",             LV_PROPERTY_STYLE_MIN_HEIGHT,},
    {"min_width",              LV_PROPERTY_STYLE_MIN_WIDTH,},
    {"opa",                    LV_PROPERTY_STYLE_OPA,},
    {"opa_layered",            LV_PROPERTY_STYLE_OPA_LAYERED,},
    {"outline_color",          LV_PROPERTY_STYLE_OUTLINE_COLOR,},
    {"outline_opa",            LV_PROPERTY_STYLE_OUTLINE_OPA,},
    {"outline_pad",            LV_PROPERTY_STYLE_OUTLINE_PAD,},
    {"outline_width",          LV_PROPERTY_STYLE_OUTLINE_WIDTH,},
    {"pad_bottom",             LV_PROPERTY_STYLE_PAD_BOTTOM,},
    {"pad_column",             LV_PROPERTY_STYLE_PAD_COLUMN,},
    {"pad_left",               LV_PROPERTY_STYLE_PAD_LEFT,},
    {"pad_right",              LV_PROPERTY_STYLE_PAD_RIGHT,},
    {"pad_row",                LV_PROPERTY_STYLE_PAD_ROW,},
    {"pad_top",                LV_PROPERTY_STYLE_PAD_TOP,},
    {"prop_inv",               LV_PROPERTY_STYLE_PROP_INV,},
    {"radius",                 LV_PROPERTY_STYLE_RADIUS,},
    {"rotary_sensitivity",     LV_PROPERTY_STYLE_ROTARY_SENSITIVITY,},
    {"shadow_color",           LV_PROPERTY_STYLE_SHADOW_COLOR,},
    {"shadow_offset_x",        LV_PROPERTY_STYLE_SHADOW_OFFSET_X,},
    {"shadow_offset_y",        LV_PROPERTY_STYLE_SHADOW_OFFSET_Y,},
    {"shadow_opa",             LV_PROPERTY_STYLE_SHADOW_OPA,},
    {"shadow_spread",          LV_PROPERTY_STYLE_SHADOW_SPREAD,},
    {"shadow_width",           LV_PROPERTY_STYLE_SHADOW_WIDTH,},
    {"text_align",             LV_PROPERTY_STYLE_TEXT_ALIGN,},
    {"text_color",             LV_PROPERTY_STYLE_TEXT_COLOR,},
    {"text_decor",             LV_PROPERTY_STYLE_TEXT_DECOR,},
    {"text_font",              LV_PROPERTY_STYLE_TEXT_FONT,},
    {"text_letter_space",      LV_PROPERTY_STYLE_TEXT_LETTER_SPACE,},
    {"text_line_space",        LV_PROPERTY_STYLE_TEXT_LINE_SPACE,},
    {"text_opa",               LV_PROPERTY_STYLE_TEXT_OPA,},
    {"transform_height",       LV_PROPERTY_STYLE_TRANSFORM_HEIGHT,},
    {"transform_pivot_x",      LV_PROPERTY_STYLE_TRANSFORM_PIVOT_X,},
    {"transform_pivot_y",      LV_PROPERTY_STYLE_TRANSFORM_PIVOT_Y,},
    {"transform_rotation",     LV_PROPERTY_STYLE_TRANSFORM_ROTATION,},
    {"transform_scale_x",      LV_PROPERTY_STYLE_TRANSFORM_SCALE_X,},
    {"transform_scale_y",      LV_PROPERTY_STYLE_TRANSFORM_SCALE_Y,},
    {"transform_skew_x",       LV_PROPERTY_STYLE_TRANSFORM_SKEW_X,},
    {"transform_skew_y",       LV_PROPERTY_STYLE_TRANSFORM_SKEW_Y,},
    {"transform_width",        LV_PROPERTY_STYLE_TRANSFORM_WIDTH,},
    {"transition",             LV_PROPERTY_STYLE_TRANSITION,},
    {"translate_x",            LV_PROPERTY_STYLE_TRANSLATE_X,},
    {"translate_y",            LV_PROPERTY_STYLE_TRANSLATE_Y,},
    {"width",                  LV_PROPERTY_STYLE_WIDTH,},
    {"x",                      LV_PROPERTY_STYLE_X,},
    {"y",                      LV_PROPERTY_STYLE_Y,},
};
/* *INDENT-ON* */
#endif
