tasks:
  - before: platformio upgrade
  - command: platformio run -e tasmota

image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - Atishay-Jain.All-Autocomplete
    - CoenraadS.bracket-pair-colorizer
    - esbenp.prettier-vscode
    - shardulm94.trailing-spaces
