/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define THORVG_CAPI_BINDING_SUPPORT 1

#define THORVG_SVG_LOADER_SUPPORT 1

#define THORVG_SW_RASTER_SUPPORT 1

#define THORVG_VERSION_STRING "0.11.99"

