#include "be_constobj.h"

static be_define_const_map_slots(be_class_lv_style_map) {
    { be_const_key(set_line_dash_width, -1), be_const_func(lvbe_style_set_line_dash_width) },
    { be_const_key(set_bg_grad_dir, -1), be_const_func(lvbe_style_set_bg_grad_dir) },
    { be_const_key(set_text_blend_mode, 84), be_const_func(lvbe_style_set_text_blend_mode) },
    { be_const_key(set_border_blend_mode, 75), be_const_func(lvbe_style_set_border_blend_mode) },
    { be_const_key(set_bg_main_stop, -1), be_const_func(lvbe_style_set_bg_main_stop) },
    { be_const_key(list_get_local_style, -1), be_const_func(lvbe_style_list_get_local_style) },
    { be_const_key(set_transform_height, 40), be_const_func(lvbe_style_set_transform_height) },
    { be_const_key(set_shadow_opa, 33), be_const_func(lvbe_style_set_shadow_opa) },
    { be_const_key(set_value_blend_mode, 51), be_const_func(lvbe_style_set_value_blend_mode) },
    { be_const_key(set_shadow_ofs_x, -1), be_const_func(lvbe_style_set_shadow_ofs_x) },
    { be_const_key(set_pattern_blend_mode, -1), be_const_func(lvbe_style_set_pattern_blend_mode) },
    { be_const_key(set_text_letter_space, -1), be_const_func(lvbe_style_set_text_letter_space) },
    { be_const_key(set_margin_right, 14), be_const_func(lvbe_style_set_margin_right) },
    { be_const_key(set_transition_delay, -1), be_const_func(lvbe_style_set_transition_delay) },
    { be_const_key(set_shadow_blend_mode, -1), be_const_func(lvbe_style_set_shadow_blend_mode) },
    { be_const_key(set_value_color, -1), be_const_func(lvbe_style_set_value_color) },
    { be_const_key(set_text_line_space, -1), be_const_func(lvbe_style_set_text_line_space) },
    { be_const_key(set_transition_prop_1, -1), be_const_func(lvbe_style_set_transition_prop_1) },
    { be_const_key(set_pattern_image, 47), be_const_func(lvbe_style_set_pattern_image) },
    { be_const_key(set_image_recolor, -1), be_const_func(lvbe_style_set_image_recolor) },
    { be_const_key(set_pattern_opa, -1), be_const_func(lvbe_style_set_pattern_opa) },
    { be_const_key(set_outline_blend_mode, -1), be_const_func(lvbe_style_set_outline_blend_mode) },
    { be_const_key(set_radius, -1), be_const_func(lvbe_style_set_radius) },
    { be_const_key(set_text_color, -1), be_const_func(lvbe_style_set_text_color) },
    { be_const_key(set_pattern_repeat, -1), be_const_func(lvbe_style_set_pattern_repeat) },
    { be_const_key(set_value_align, -1), be_const_func(lvbe_style_set_value_align) },
    { be_const_key(set_scale_width, 82), be_const_func(lvbe_style_set_scale_width) },
    { be_const_key(set_line_color, -1), be_const_func(lvbe_style_set_line_color) },
    { be_const_key(set_text_opa, 4), be_const_func(lvbe_style_set_text_opa) },
    { be_const_key(set_size, -1), be_const_func(lvbe_style_set_size) },
    { be_const_key(set_border_opa, 72), be_const_func(lvbe_style_set_border_opa) },
    { be_const_key(set_line_opa, 12), be_const_func(lvbe_style_set_line_opa) },
    { be_const_key(set_pad_inner, -1), be_const_func(lvbe_style_set_pad_inner) },
    { be_const_key(set_margin_bottom, -1), be_const_func(lvbe_style_set_margin_bottom) },
    { be_const_key(set_margin_top, 66), be_const_func(lvbe_style_set_margin_top) },
    { be_const_key(init, -1), be_const_func(lvs_init) },
    { be_const_key(set_transition_prop_2, -1), be_const_func(lvbe_style_set_transition_prop_2) },
    { be_const_key(set_transition_prop_5, -1), be_const_func(lvbe_style_set_transition_prop_5) },
    { be_const_key(set_transition_prop_6, 26), be_const_func(lvbe_style_set_transition_prop_6) },
    { be_const_key(set_border_post, 30), be_const_func(lvbe_style_set_border_post) },
    { be_const_key(set_scale_end_line_width, -1), be_const_func(lvbe_style_set_scale_end_line_width) },
    { be_const_key(set_pad_left, 64), be_const_func(lvbe_style_set_pad_left) },
    { be_const_key(set_scale_border_width, -1), be_const_func(lvbe_style_set_scale_border_width) },
    { be_const_key(set_line_blend_mode, 34), be_const_func(lvbe_style_set_line_blend_mode) },
    { be_const_key(set_image_recolor_opa, -1), be_const_func(lvbe_style_set_image_recolor_opa) },
    { be_const_key(set_bg_color, -1), be_const_func(lvbe_style_set_bg_color) },
    { be_const_key(set_pad_bottom, -1), be_const_func(lvbe_style_set_pad_bottom) },
    { be_const_key(set_transition_time, -1), be_const_func(lvbe_style_set_transition_time) },
    { be_const_key(set_outline_pad, 67), be_const_func(lvbe_style_set_outline_pad) },
    { be_const_key(set_transform_angle, 32), be_const_func(lvbe_style_set_transform_angle) },
    { be_const_key(set_value_line_space, -1), be_const_func(lvbe_style_set_value_line_space) },
    { be_const_key(set_image_opa, 76), be_const_func(lvbe_style_set_image_opa) },
    { be_const_key(set_pattern_recolor, -1), be_const_func(lvbe_style_set_pattern_recolor) },
    { be_const_key(set_bg_grad_color, 85), be_const_func(lvbe_style_set_bg_grad_color) },
    { be_const_key(set_value_letter_space, -1), be_const_func(lvbe_style_set_value_letter_space) },
    { be_const_key(set_shadow_spread, 0), be_const_func(lvbe_style_set_shadow_spread) },
    { be_const_key(set_text_font, 97), be_const_func(lvbe_style_set_text_font) },
    { be_const_key(set_line_width, -1), be_const_func(lvbe_style_set_line_width) },
    { be_const_key(set_shadow_color, -1), be_const_func(lvbe_style_set_shadow_color) },
    { be_const_key(set_transform_zoom, -1), be_const_func(lvbe_style_set_transform_zoom) },
    { be_const_key(set_outline_color, 79), be_const_func(lvbe_style_set_outline_color) },
    { be_const_key(set_shadow_ofs_y, 87), be_const_func(lvbe_style_set_shadow_ofs_y) },
    { be_const_key(set_text_sel_bg_color, -1), be_const_func(lvbe_style_set_text_sel_bg_color) },
    { be_const_key(set_text_decor, -1), be_const_func(lvbe_style_set_text_decor) },
    { be_const_key(tostring, -1), be_const_func(lvs_tostring) },
    { be_const_key(set_clip_corner, -1), be_const_func(lvbe_style_set_clip_corner) },
    { be_const_key(set_value_str, -1), be_const_func(lvbe_style_set_value_str) },
    { be_const_key(set_pattern_recolor_opa, 16), be_const_func(lvbe_style_set_pattern_recolor_opa) },
    { be_const_key(set_border_side, -1), be_const_func(lvbe_style_set_border_side) },
    { be_const_key(set_scale_grad_color, -1), be_const_func(lvbe_style_set_scale_grad_color) },
    { be_const_key(set_line_rounded, 10), be_const_func(lvbe_style_set_line_rounded) },
    { be_const_key(set_pad_right, 35), be_const_func(lvbe_style_set_pad_right) },
    { be_const_key(set_transition_prop_4, -1), be_const_func(lvbe_style_set_transition_prop_4) },
    { be_const_key(set_transition_prop_3, 99), be_const_func(lvbe_style_set_transition_prop_3) },
    { be_const_key(list_init, -1), be_const_func(lvbe_style_list_init) },
    { be_const_key(set_transform_width, -1), be_const_func(lvbe_style_set_transform_width) },
    { be_const_key(set_bg_grad_stop, -1), be_const_func(lvbe_style_set_bg_grad_stop) },
    { be_const_key(dot_p, -1), be_const_int(0) },
    { be_const_key(set_value_opa, 50), be_const_func(lvbe_style_set_value_opa) },
    { be_const_key(set_value_font, -1), be_const_func(lvbe_style_set_value_font) },
    { be_const_key(set_text_sel_color, -1), be_const_func(lvbe_style_set_text_sel_color) },
    { be_const_key(set_outline_width, -1), be_const_func(lvbe_style_set_outline_width) },
    { be_const_key(set_value_ofs_x, 11), be_const_func(lvbe_style_set_value_ofs_x) },
    { be_const_key(set_scale_end_color, -1), be_const_func(lvbe_style_set_scale_end_color) },
    { be_const_key(set_margin_left, -1), be_const_func(lvbe_style_set_margin_left) },
    { be_const_key(copy, -1), be_const_func(lvbe_style_copy) },
    { be_const_key(set_shadow_width, -1), be_const_func(lvbe_style_set_shadow_width) },
    { be_const_key(set_bg_opa, -1), be_const_func(lvbe_style_set_bg_opa) },
    { be_const_key(list_copy, 73), be_const_func(lvbe_style_list_copy) },
    { be_const_key(set_value_ofs_y, 17), be_const_func(lvbe_style_set_value_ofs_y) },
    { be_const_key(set_opa_scale, 15), be_const_func(lvbe_style_set_opa_scale) },
    { be_const_key(set_scale_end_border_width, 37), be_const_func(lvbe_style_set_scale_end_border_width) },
    { be_const_key(set_border_color, 81), be_const_func(lvbe_style_set_border_color) },
    { be_const_key(set_line_dash_gap, 95), be_const_func(lvbe_style_set_line_dash_gap) },
    { be_const_key(set_bg_blend_mode, -1), be_const_func(lvbe_style_set_bg_blend_mode) },
    { be_const_key(remove_prop, 77), be_const_func(lvbe_style_remove_prop) },
    { be_const_key(set_border_width, -1), be_const_func(lvbe_style_set_border_width) },
    { be_const_key(set_image_blend_mode, -1), be_const_func(lvbe_style_set_image_blend_mode) },
    { be_const_key(set_transition_path, -1), be_const_func(lvbe_style_set_transition_path) },
    { be_const_key(set_outline_opa, 29), be_const_func(lvbe_style_set_outline_opa) },
    { be_const_key(reset, -1), be_const_func(lvbe_style_reset) },
    { be_const_key(set_pad_top, 45), be_const_func(lvbe_style_set_pad_top) },
    { be_const_key(list_get_style, -1), be_const_func(lvbe_style_list_get_style) },
};

static be_define_const_map(
    be_class_lv_style_map,
    103
);

BE_EXPORT_VARIABLE be_define_const_class(
    be_class_lv_style,
    1,
    (bclass *)&be_class_lv_obj,
    lv_style
);
