/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: cosmos/crypto/multisig/v1beta1/multisig.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "cosmos/crypto/multisig/v1beta1/multisig.pb-c.h"
void   cosmos__crypto__multisig__v1beta1__multi_signature__init
                     (Cosmos__Crypto__Multisig__V1beta1__MultiSignature         *message)
{
  static const Cosmos__Crypto__Multisig__V1beta1__MultiSignature init_value = COSMOS__CRYPTO__MULTISIG__V1BETA1__MULTI_SIGNATURE__INIT;
  *message = init_value;
}
size_t cosmos__crypto__multisig__v1beta1__multi_signature__get_packed_size
                     (const Cosmos__Crypto__Multisig__V1beta1__MultiSignature *message)
{
  assert(message->base.descriptor == &cosmos__crypto__multisig__v1beta1__multi_signature__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cosmos__crypto__multisig__v1beta1__multi_signature__pack
                     (const Cosmos__Crypto__Multisig__V1beta1__MultiSignature *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cosmos__crypto__multisig__v1beta1__multi_signature__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cosmos__crypto__multisig__v1beta1__multi_signature__pack_to_buffer
                     (const Cosmos__Crypto__Multisig__V1beta1__MultiSignature *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cosmos__crypto__multisig__v1beta1__multi_signature__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Cosmos__Crypto__Multisig__V1beta1__MultiSignature *
       cosmos__crypto__multisig__v1beta1__multi_signature__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Cosmos__Crypto__Multisig__V1beta1__MultiSignature *)
     protobuf_c_message_unpack (&cosmos__crypto__multisig__v1beta1__multi_signature__descriptor,
                                allocator, len, data);
}
void   cosmos__crypto__multisig__v1beta1__multi_signature__free_unpacked
                     (Cosmos__Crypto__Multisig__V1beta1__MultiSignature *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &cosmos__crypto__multisig__v1beta1__multi_signature__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cosmos__crypto__multisig__v1beta1__compact_bit_array__init
                     (Cosmos__Crypto__Multisig__V1beta1__CompactBitArray         *message)
{
  static const Cosmos__Crypto__Multisig__V1beta1__CompactBitArray init_value = COSMOS__CRYPTO__MULTISIG__V1BETA1__COMPACT_BIT_ARRAY__INIT;
  *message = init_value;
}
size_t cosmos__crypto__multisig__v1beta1__compact_bit_array__get_packed_size
                     (const Cosmos__Crypto__Multisig__V1beta1__CompactBitArray *message)
{
  assert(message->base.descriptor == &cosmos__crypto__multisig__v1beta1__compact_bit_array__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cosmos__crypto__multisig__v1beta1__compact_bit_array__pack
                     (const Cosmos__Crypto__Multisig__V1beta1__CompactBitArray *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cosmos__crypto__multisig__v1beta1__compact_bit_array__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cosmos__crypto__multisig__v1beta1__compact_bit_array__pack_to_buffer
                     (const Cosmos__Crypto__Multisig__V1beta1__CompactBitArray *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cosmos__crypto__multisig__v1beta1__compact_bit_array__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Cosmos__Crypto__Multisig__V1beta1__CompactBitArray *
       cosmos__crypto__multisig__v1beta1__compact_bit_array__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Cosmos__Crypto__Multisig__V1beta1__CompactBitArray *)
     protobuf_c_message_unpack (&cosmos__crypto__multisig__v1beta1__compact_bit_array__descriptor,
                                allocator, len, data);
}
void   cosmos__crypto__multisig__v1beta1__compact_bit_array__free_unpacked
                     (Cosmos__Crypto__Multisig__V1beta1__CompactBitArray *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &cosmos__crypto__multisig__v1beta1__compact_bit_array__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor cosmos__crypto__multisig__v1beta1__multi_signature__field_descriptors[1] =
{
  {
    "signatures",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Cosmos__Crypto__Multisig__V1beta1__MultiSignature, n_signatures),
    offsetof(Cosmos__Crypto__Multisig__V1beta1__MultiSignature, signatures),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cosmos__crypto__multisig__v1beta1__multi_signature__field_indices_by_name[] = {
  0,   /* field[0] = signatures */
};
static const ProtobufCIntRange cosmos__crypto__multisig__v1beta1__multi_signature__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor cosmos__crypto__multisig__v1beta1__multi_signature__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "cosmos.crypto.multisig.v1beta1.MultiSignature",
  "MultiSignature",
  "Cosmos__Crypto__Multisig__V1beta1__MultiSignature",
  "cosmos.crypto.multisig.v1beta1",
  sizeof(Cosmos__Crypto__Multisig__V1beta1__MultiSignature),
  1,
  cosmos__crypto__multisig__v1beta1__multi_signature__field_descriptors,
  cosmos__crypto__multisig__v1beta1__multi_signature__field_indices_by_name,
  1,  cosmos__crypto__multisig__v1beta1__multi_signature__number_ranges,
  (ProtobufCMessageInit) cosmos__crypto__multisig__v1beta1__multi_signature__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cosmos__crypto__multisig__v1beta1__compact_bit_array__field_descriptors[2] =
{
  {
    "extra_bits_stored",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Cosmos__Crypto__Multisig__V1beta1__CompactBitArray, extra_bits_stored),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "elems",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Cosmos__Crypto__Multisig__V1beta1__CompactBitArray, elems),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cosmos__crypto__multisig__v1beta1__compact_bit_array__field_indices_by_name[] = {
  1,   /* field[1] = elems */
  0,   /* field[0] = extra_bits_stored */
};
static const ProtobufCIntRange cosmos__crypto__multisig__v1beta1__compact_bit_array__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor cosmos__crypto__multisig__v1beta1__compact_bit_array__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "cosmos.crypto.multisig.v1beta1.CompactBitArray",
  "CompactBitArray",
  "Cosmos__Crypto__Multisig__V1beta1__CompactBitArray",
  "cosmos.crypto.multisig.v1beta1",
  sizeof(Cosmos__Crypto__Multisig__V1beta1__CompactBitArray),
  2,
  cosmos__crypto__multisig__v1beta1__compact_bit_array__field_descriptors,
  cosmos__crypto__multisig__v1beta1__compact_bit_array__field_indices_by_name,
  1,  cosmos__crypto__multisig__v1beta1__compact_bit_array__number_ranges,
  (ProtobufCMessageInit) cosmos__crypto__multisig__v1beta1__compact_bit_array__init,
  NULL,NULL,NULL    /* reserved[123] */
};
