/********************************************************************
 * Generated code, don't edit
 *******************************************************************/
/********************************************************************
 * LVGL Module
 *******************************************************************/
#include "be_constobj.h"

#include "lvgl.h"
#include "be_mapping.h"
#include "be_ctypes.h"
#include "lv_berry.h"
#include "lv_theme_haspmota.h"

// declare accessors for non-const ints
int32_t be_LV_LAYOUT_GRID(void) { return LV_LAYOUT_GRID; };              BE_VAR_CTYPE_DECLARE(be_LV_LAYOUT_GRID, "i");
int32_t be_LV_LAYOUT_FLEX(void) { return LV_LAYOUT_FLEX; };              BE_VAR_CTYPE_DECLARE(be_LV_LAYOUT_FLEX, "i");

extern int lv0_member(bvm *vm);     // resolve virtual members
extern int lv0_load_font(bvm *vm);

extern lv_ts_calibration_t * lv_get_ts_calibration(void);

static int lv_get_hor_res(void) {
  return lv_disp_get_hor_res(lv_disp_get_default());
}
static int lv_get_ver_res(void) {
  return lv_disp_get_ver_res(lv_disp_get_default());
}

/* `lv` methods */
const be_ntv_func_def_t lv_func[] = {

  { "anim_count_running", { (const void*) &lv_anim_count_running, "i", "" } },
  { "anim_del", { (const void*) &lv_anim_del, "b", ".c" } },
  { "anim_del_all", { (const void*) &lv_anim_del_all, "", "" } },
  { "anim_get", { (const void*) &lv_anim_get, "lv.lv_anim", ".c" } },
  { "anim_get_timer", { (const void*) &lv_anim_get_timer, "lv.lv_timer", "" } },
  { "anim_refr_now", { (const void*) &lv_anim_refr_now, "", "" } },
  { "anim_speed_to_time", { (const void*) &lv_anim_speed_to_time, "i", "iii" } },
  { "area_align", { (const void*) &lv_area_align, "", "(lv.lv_area)(lv.lv_area)iii" } },
  { "area_copy", { (const void*) &lv_area_copy, "", "(lv.lv_area)(lv.lv_area)" } },
  { "area_get_height", { (const void*) &lv_area_get_height, "i", "(lv.lv_area)" } },
  { "area_get_size", { (const void*) &lv_area_get_size, "i", "(lv.lv_area)" } },
  { "area_get_width", { (const void*) &lv_area_get_width, "i", "(lv.lv_area)" } },
  { "area_increase", { (const void*) &lv_area_increase, "", "(lv.lv_area)ii" } },
  { "area_move", { (const void*) &lv_area_move, "", "(lv.lv_area)ii" } },
  { "area_set", { (const void*) &lv_area_set, "", "(lv.lv_area)iiii" } },
  { "area_set_height", { (const void*) &lv_area_set_height, "", "(lv.lv_area)i" } },
  { "area_set_width", { (const void*) &lv_area_set_width, "", "(lv.lv_area)i" } },
  { "atan2", { (const void*) &lv_atan2, "i", "ii" } },
  { "bezier3", { (const void*) &lv_bezier3, "i", "iiiii" } },
  { "clamp_height", { (const void*) &lv_clamp_height, "i", "iiii" } },
  { "clamp_width", { (const void*) &lv_clamp_width, "i", "iiii" } },
  { "color_black", { (const void*) &lv_color_black, "lv.lv_color", "" } },
  { "color_brightness", { (const void*) &lv_color_brightness, "i", "(lv.lv_color)" } },
  { "color_change_lightness", { (const void*) &lv_color_change_lightness, "lv.lv_color", "(lv.lv_color)i" } },
  { "color_chroma_key", { (const void*) &lv_color_chroma_key, "lv.lv_color", "" } },
  { "color_darken", { (const void*) &lv_color_darken, "lv.lv_color", "(lv.lv_color)i" } },
  { "color_fill", { (const void*) &lv_color_fill, "", "(lv.lv_color)(lv.lv_color)i" } },
  { "color_filter_dsc_init", { (const void*) &lv_color_filter_dsc_init, "", "(lv.lv_color_filter_dsc)^lv_color_filter_cb^" } },
  { "color_hex", { (const void*) &lv_color_hex, "lv.lv_color", "i" } },
  { "color_hex3", { (const void*) &lv_color_hex3, "lv.lv_color", "i" } },
  { "color_hsv_to_rgb", { (const void*) &lv_color_hsv_to_rgb, "lv.lv_color", "iii" } },
  { "color_lighten", { (const void*) &lv_color_lighten, "lv.lv_color", "(lv.lv_color)i" } },
  { "color_make", { (const void*) &lv_color_make, "lv.lv_color", "iii" } },
  { "color_mix", { (const void*) &lv_color_mix, "lv.lv_color", "(lv.lv_color)(lv.lv_color)i" } },
  { "color_mix_premult", { (const void*) &lv_color_mix_premult, "lv.lv_color", "(lv.uint16)(lv.lv_color)i" } },
  { "color_mix_with_alpha", { (const void*) &lv_color_mix_with_alpha, "", "(lv.lv_color)i(lv.lv_color)i(lv.lv_color)(lv.lv_opa)" } },
  { "color_premult", { (const void*) &lv_color_premult, "", "(lv.lv_color)i(lv.uint16)" } },
  { "color_rgb_to_hsv", { (const void*) &lv_color_rgb_to_hsv, "i", "iii" } },
  { "color_to1", { (const void*) &lv_color_to1, "i", "(lv.lv_color)" } },
  { "color_to16", { (const void*) &lv_color_to16, "i", "(lv.lv_color)" } },
  { "color_to32", { (const void*) &lv_color_to32, "i", "(lv.lv_color)" } },
  { "color_to8", { (const void*) &lv_color_to8, "i", "(lv.lv_color)" } },
  { "color_to_hsv", { (const void*) &lv_color_to_hsv, "i", "(lv.lv_color)" } },
  { "color_white", { (const void*) &lv_color_white, "lv.lv_color", "" } },
  { "dpx", { (const void*) &lv_dpx, "i", "i" } },
  { "draw_arc", { (const void*) &lv_draw_arc, "", "(lv.lv_draw_ctx)(lv.lv_draw_arc_dsc)(lv.lv_point)iii" } },
  { "draw_arc_dsc_init", { (const void*) &lv_draw_arc_dsc_init, "", "(lv.lv_draw_arc_dsc)" } },
  { "draw_arc_get_area", { (const void*) &lv_draw_arc_get_area, "", "iiiiiib(lv.lv_area)" } },
  { "draw_img", { (const void*) &lv_draw_img, "", "(lv.lv_draw_ctx)(lv.lv_draw_img_dsc)(lv.lv_area)." } },
  { "draw_img_decoded", { (const void*) &lv_draw_img_decoded, "", "(lv.lv_draw_ctx)(lv.lv_draw_img_dsc)(lv.lv_area)ci" } },
  { "draw_img_dsc_init", { (const void*) &lv_draw_img_dsc_init, "", "(lv.lv_draw_img_dsc)" } },
  { "draw_init", { (const void*) &lv_draw_init, "", "" } },
  { "draw_label", { (const void*) &lv_draw_label, "", "(lv.lv_draw_ctx)(lv.lv_draw_label_dsc)(lv.lv_area)s(lv.lv_draw_label_hint)" } },
  { "draw_label_dsc_init", { (const void*) &lv_draw_label_dsc_init, "", "(lv.lv_draw_label_dsc)" } },
  { "draw_layer_adjust", { (const void*) &lv_draw_layer_adjust, "", "(lv.lv_draw_ctx)(lv.lv_draw_layer_ctx)(lv.lv_draw_layer_flags)" } },
  { "draw_layer_blend", { (const void*) &lv_draw_layer_blend, "", "(lv.lv_draw_ctx)(lv.lv_draw_layer_ctx)(lv.lv_draw_img_dsc)" } },
  { "draw_layer_create", { (const void*) &lv_draw_layer_create, "lv.lv_draw_layer_ctx", "(lv.lv_draw_ctx)(lv.lv_area)(lv.lv_draw_layer_flags)" } },
  { "draw_layer_destroy", { (const void*) &lv_draw_layer_destroy, "", "(lv.lv_draw_ctx)(lv.lv_draw_layer_ctx)" } },
  { "draw_letter", { (const void*) &lv_draw_letter, "", "(lv.lv_draw_ctx)(lv.lv_draw_label_dsc)(lv.lv_point)i" } },
  { "draw_line", { (const void*) &lv_draw_line, "", "(lv.lv_draw_ctx)(lv.lv_draw_line_dsc)(lv.lv_point)(lv.lv_point)" } },
  { "draw_line_dsc_init", { (const void*) &lv_draw_line_dsc_init, "", "(lv.lv_draw_line_dsc)" } },
  { "draw_mask_add", { (const void*) &lv_draw_mask_add, "i", ".." } },
  { "draw_mask_angle_init", { (const void*) &lv_draw_mask_angle_init, "", "(lv.lv_draw_mask_angle_param)iiii" } },
  { "draw_mask_apply", { (const void*) &lv_draw_mask_apply, "i", "(lv.lv_opa)iii" } },
  { "draw_mask_apply_ids", { (const void*) &lv_draw_mask_apply_ids, "i", "(lv.lv_opa)iii(lv.int16)i" } },
  { "draw_mask_fade_init", { (const void*) &lv_draw_mask_fade_init, "", "(lv.lv_draw_mask_fade_param)(lv.lv_area)iiii" } },
  { "draw_mask_free_param", { (const void*) &lv_draw_mask_free_param, "", "." } },
  { "draw_mask_get_cnt", { (const void*) &lv_draw_mask_get_cnt, "i", "" } },
  { "draw_mask_is_any", { (const void*) &lv_draw_mask_is_any, "b", "(lv.lv_area)" } },
  { "draw_mask_line_angle_init", { (const void*) &lv_draw_mask_line_angle_init, "", "(lv.lv_draw_mask_line_param)iiii" } },
  { "draw_mask_line_points_init", { (const void*) &lv_draw_mask_line_points_init, "", "(lv.lv_draw_mask_line_param)iiiii" } },
  { "draw_mask_map_init", { (const void*) &lv_draw_mask_map_init, "", "(lv.lv_draw_mask_map_param)(lv.lv_area)(lv.lv_opa)" } },
  { "draw_mask_polygon_init", { (const void*) &lv_draw_mask_polygon_init, "", "(lv.lv_draw_mask_polygon_param)(lv.lv_point)i" } },
  { "draw_mask_radius_init", { (const void*) &lv_draw_mask_radius_init, "", "(lv.lv_draw_mask_radius_param)(lv.lv_area)ib" } },
  { "draw_mask_remove_custom", { (const void*) &lv_draw_mask_remove_custom, ".", "." } },
  { "draw_mask_remove_id", { (const void*) &lv_draw_mask_remove_id, ".", "i" } },
  { "draw_polygon", { (const void*) &lv_draw_polygon, "", "(lv.lv_draw_ctx)(lv.lv_draw_rect_dsc)(lv.lv_point_arr)i" } },
  { "draw_rect", { (const void*) &lv_draw_rect, "", "(lv.lv_draw_ctx)(lv.lv_draw_rect_dsc)(lv.lv_area)" } },
  { "draw_rect_dsc_init", { (const void*) &lv_draw_rect_dsc_init, "", "(lv.lv_draw_rect_dsc)" } },
  { "draw_transform", { (const void*) &lv_draw_transform, "", "(lv.lv_draw_ctx)(lv.lv_area).iii(lv.lv_draw_img_dsc)i(lv.lv_color)(lv.lv_opa)" } },
  { "draw_triangle", { (const void*) &lv_draw_triangle, "", "(lv.lv_draw_ctx)(lv.lv_draw_rect_dsc)(lv.lv_point_arr)" } },
  { "draw_wait_for_finish", { (const void*) &lv_draw_wait_for_finish, "", "(lv.lv_draw_ctx)" } },
  { "event_register_id", { (const void*) &lv_event_register_id, "i", "" } },
  { "event_send", { (const void*) &lv_event_send, "i", "(lv.lv_obj)i." } },
  { "event_set_cover_res", { (const void*) &lv_event_set_cover_res, "", "(lv.lv_event)(lv.lv_cover_res)" } },
  { "event_set_ext_draw_size", { (const void*) &lv_event_set_ext_draw_size, "", "(lv.lv_event)i" } },
  { "event_stop_bubbling", { (const void*) &lv_event_stop_bubbling, "", "(lv.lv_event)" } },
  { "event_stop_processing", { (const void*) &lv_event_stop_processing, "", "(lv.lv_event)" } },
  { "flex_init", { (const void*) &lv_flex_init, "", "" } },
  { "font_get_glyph_bitmap", { (const void*) &lv_font_get_glyph_bitmap, "c", "(lv.lv_font)i" } },
  { "font_get_glyph_dsc", { (const void*) &lv_font_get_glyph_dsc, "b", "(lv.lv_font)(lv.lv_font_glyph_dsc)ii" } },
  { "font_get_glyph_width", { (const void*) &lv_font_get_glyph_width, "i", "(lv.lv_font)ii" } },
  { "font_get_line_height", { (const void*) &lv_font_get_line_height, "i", "(lv.lv_font)" } },
  { "get_hor_res", { (const void*) &lv_get_hor_res, "i", "" } },
  { "get_ts_calibration", { (const void*) &lv_get_ts_calibration, "lv.lv_ts_calibration", "" } },
  { "get_ver_res", { (const void*) &lv_get_ver_res, "i", "" } },
  { "grid_fr", { (const void*) &lv_grid_fr, "i", "i" } },
  { "grid_init", { (const void*) &lv_grid_init, "", "" } },
  { "group_get_default", { (const void*) &lv_group_get_default, "lv.lv_group", "" } },
  { "img_src_get_type", { (const void*) &lv_img_src_get_type, "i", "." } },
  { "indev_get_act", { (const void*) &lv_indev_get_act, "lv.lv_indev", "" } },
  { "indev_get_obj_act", { (const void*) &lv_indev_get_obj_act, "lv.lv_obj", "" } },
  { "indev_get_read_timer", { (const void*) &lv_indev_get_read_timer, "lv.lv_timer", "(lv.lv_disp)" } },
  { "indev_read_timer_cb", { (const void*) &lv_indev_read_timer_cb, "", "(lv.lv_timer)" } },
  { "is_initialized", { (const void*) &lv_is_initialized, "b", "" } },
  { "layer_sys", { (const void*) &lv_layer_sys, "lv.lv_obj", "" } },
  { "layer_top", { (const void*) &lv_layer_top, "lv.lv_obj", "" } },
  { "layout_register", { (const void*) &lv_layout_register, "i", "^lv_layout_update_cb^." } },
  { "map", { (const void*) &lv_map, "i", "iiiii" } },
  { "obj_class_create_obj", { (const void*) &lv_obj_class_create_obj, "lv.lv_obj", "(lv._lv_obj_class)(lv.lv_obj)" } },
  { "obj_del_anim_ready_cb", { (const void*) &lv_obj_del_anim_ready_cb, "", "(lv.lv_anim)" } },
  { "obj_draw_dsc_init", { (const void*) &lv_obj_draw_dsc_init, "", "(lv.lv_obj_draw_part_dsc)(lv.lv_draw_ctx)" } },
  { "obj_draw_part_check_type", { (const void*) &lv_obj_draw_part_check_type, "b", "(lv.lv_obj_draw_part_dsc)(lv._lv_obj_class)i" } },
  { "obj_enable_style_refresh", { (const void*) &lv_obj_enable_style_refresh, "", "b" } },
  { "obj_event_base", { (const void*) &lv_obj_event_base, "i", "(lv.lv_obj_class)(lv.lv_event)" } },
  { "obj_redraw", { (const void*) &lv_obj_redraw, "", "(lv.lv_draw_ctx)(lv.lv_obj)" } },
  { "obj_report_style_change", { (const void*) &lv_obj_report_style_change, "", "(lv.lv_style)" } },
  { "obj_style_get_selector_part", { (const void*) &lv_obj_style_get_selector_part, "i", "i" } },
  { "obj_style_get_selector_state", { (const void*) &lv_obj_style_get_selector_state, "i", "i" } },
  { "palette_darken", { (const void*) &lv_palette_darken, "lv.lv_color", "ii" } },
  { "palette_lighten", { (const void*) &lv_palette_lighten, "lv.lv_color", "ii" } },
  { "palette_main", { (const void*) &lv_palette_main, "lv.lv_color", "i" } },
  { "pct", { (const void*) &lv_pct, "i", "i" } },
  { "point_transform", { (const void*) &lv_point_transform, "", "(lv.lv_point)ii(lv.lv_point)" } },
  { "rand", { (const void*) &lv_rand, "i", "ii" } },
  { "refr_now", { (const void*) &lv_refr_now, "", "(lv.lv_disp)" } },
  { "scr_act", { (const void*) &lv_scr_act, "lv.lv_obj", "" } },
  { "scr_load", { (const void*) &lv_scr_load, "", "(lv.lv_obj)" } },
  { "scr_load_anim", { (const void*) &lv_scr_load_anim, "", "(lv.lv_obj)iiib" } },
  { "sqrt", { (const void*) &lv_sqrt, "", "i(lv.lv_sqrt_res)i" } },
  { "style_get_num_custom_props", { (const void*) &lv_style_get_num_custom_props, "i", "" } },
  { "style_prop_get_default", { (const void*) &lv_style_prop_get_default, "i", "i" } },
  { "style_prop_has_flag", { (const void*) &lv_style_prop_has_flag, "b", "ii" } },
  { "style_register_prop", { (const void*) &lv_style_register_prop, "i", "i" } },
  { "style_transition_dsc_init", { (const void*) &lv_style_transition_dsc_init, "", "(lv.lv_style_transition_dsc)(lv.lv_style_prop)cii." } },
  { "task_handler", { (const void*) &lv_task_handler, "i", "" } },
  { "theme_apply", { (const void*) &lv_theme_apply, "", "(lv.lv_obj)" } },
  { "theme_default_get", { (const void*) &lv_theme_default_get, "lv.lv_theme", "" } },
  { "theme_default_init", { (const void*) &lv_theme_default_init, "lv.lv_theme", "(lv.lv_disp)(lv.lv_color)(lv.lv_color)b(lv.lv_font)" } },
  { "theme_default_is_inited", { (const void*) &lv_theme_default_is_inited, "b", "" } },
  { "theme_get_color_primary", { (const void*) &lv_theme_get_color_primary, "lv.lv_color", "(lv.lv_obj)" } },
  { "theme_get_color_secondary", { (const void*) &lv_theme_get_color_secondary, "lv.lv_color", "(lv.lv_obj)" } },
  { "theme_get_font_large", { (const void*) &lv_theme_get_font_large, "lv.lv_font", "(lv.lv_obj)" } },
  { "theme_get_font_normal", { (const void*) &lv_theme_get_font_normal, "lv.lv_font", "(lv.lv_obj)" } },
  { "theme_get_font_small", { (const void*) &lv_theme_get_font_small, "lv.lv_font", "(lv.lv_obj)" } },
  { "theme_get_from_obj", { (const void*) &lv_theme_get_from_obj, "lv.lv_theme", "(lv.lv_obj)" } },
  { "theme_haspmota_init", { (const void*) &lv_theme_haspmota_init, "lv.lv_theme", "(lv.lv_disp)(lv.lv_color)(lv.lv_color)b(lv.lv_font)" } },
  { "theme_haspmota_is_inited", { (const void*) &lv_theme_haspmota_is_inited, "b", "" } },
  { "theme_mono_init", { (const void*) &lv_theme_mono_init, "lv.lv_theme", "(lv.lv_disp)b(lv.lv_font)" } },
  { "theme_mono_is_inited", { (const void*) &lv_theme_mono_is_inited, "b", "" } },
  { "theme_set_apply_cb", { (const void*) &lv_theme_set_apply_cb, "", "(lv.lv_theme)^lv_theme_apply_cb^" } },
  { "theme_set_parent", { (const void*) &lv_theme_set_parent, "", "(lv.lv_theme)(lv.lv_theme)" } },
  { "timer_create", { (const void*) &lv_timer_create, "lv.lv_timer", "^lv_timer_cb^i." } },
  { "timer_create_basic", { (const void*) &lv_timer_create_basic, "lv.lv_timer", "" } },
  { "timer_enable", { (const void*) &lv_timer_enable, "", "b" } },
  { "timer_get_idle", { (const void*) &lv_timer_get_idle, "i", "" } },
  { "timer_handler", { (const void*) &lv_timer_handler, "i", "" } },
  { "timer_handler_run_in_period", { (const void*) &lv_timer_handler_run_in_period, "i", "i" } },
  { "trigo_cos", { (const void*) &lv_trigo_cos, "i", "i" } },
  { "trigo_sin", { (const void*) &lv_trigo_sin, "i", "i" } },

};
const size_t lv_func_size = sizeof(lv_func) / sizeof(lv_func[0]);




const be_const_member_t lv0_constants[] = {

    { "ALIGN_BOTTOM_LEFT", be_cconst_int(LV_ALIGN_BOTTOM_LEFT) },
    { "ALIGN_BOTTOM_MID", be_cconst_int(LV_ALIGN_BOTTOM_MID) },
    { "ALIGN_BOTTOM_RIGHT", be_cconst_int(LV_ALIGN_BOTTOM_RIGHT) },
    { "ALIGN_CENTER", be_cconst_int(LV_ALIGN_CENTER) },
    { "ALIGN_DEFAULT", be_cconst_int(LV_ALIGN_DEFAULT) },
    { "ALIGN_LEFT_MID", be_cconst_int(LV_ALIGN_LEFT_MID) },
    { "ALIGN_OUT_BOTTOM_LEFT", be_cconst_int(LV_ALIGN_OUT_BOTTOM_LEFT) },
    { "ALIGN_OUT_BOTTOM_MID", be_cconst_int(LV_ALIGN_OUT_BOTTOM_MID) },
    { "ALIGN_OUT_BOTTOM_RIGHT", be_cconst_int(LV_ALIGN_OUT_BOTTOM_RIGHT) },
    { "ALIGN_OUT_LEFT_BOTTOM", be_cconst_int(LV_ALIGN_OUT_LEFT_BOTTOM) },
    { "ALIGN_OUT_LEFT_MID", be_cconst_int(LV_ALIGN_OUT_LEFT_MID) },
    { "ALIGN_OUT_LEFT_TOP", be_cconst_int(LV_ALIGN_OUT_LEFT_TOP) },
    { "ALIGN_OUT_RIGHT_BOTTOM", be_cconst_int(LV_ALIGN_OUT_RIGHT_BOTTOM) },
    { "ALIGN_OUT_RIGHT_MID", be_cconst_int(LV_ALIGN_OUT_RIGHT_MID) },
    { "ALIGN_OUT_RIGHT_TOP", be_cconst_int(LV_ALIGN_OUT_RIGHT_TOP) },
    { "ALIGN_OUT_TOP_LEFT", be_cconst_int(LV_ALIGN_OUT_TOP_LEFT) },
    { "ALIGN_OUT_TOP_MID", be_cconst_int(LV_ALIGN_OUT_TOP_MID) },
    { "ALIGN_OUT_TOP_RIGHT", be_cconst_int(LV_ALIGN_OUT_TOP_RIGHT) },
    { "ALIGN_RIGHT_MID", be_cconst_int(LV_ALIGN_RIGHT_MID) },
    { "ALIGN_TOP_LEFT", be_cconst_int(LV_ALIGN_TOP_LEFT) },
    { "ALIGN_TOP_MID", be_cconst_int(LV_ALIGN_TOP_MID) },
    { "ALIGN_TOP_RIGHT", be_cconst_int(LV_ALIGN_TOP_RIGHT) },
    { "ANIM_IMG_PART_MAIN", be_cconst_int(LV_ANIM_IMG_PART_MAIN) },
    { "ANIM_OFF", be_cconst_int(LV_ANIM_OFF) },
    { "ANIM_ON", be_cconst_int(LV_ANIM_ON) },
    { "ANIM_PLAYTIME_INFINITE", be_cconst_int(LV_ANIM_PLAYTIME_INFINITE) },
    { "ANIM_REPEAT_INFINITE", be_cconst_int(LV_ANIM_REPEAT_INFINITE) },
    { "ARC_DRAW_PART_BACKGROUND", be_cconst_int(LV_ARC_DRAW_PART_BACKGROUND) },
    { "ARC_DRAW_PART_FOREGROUND", be_cconst_int(LV_ARC_DRAW_PART_FOREGROUND) },
    { "ARC_DRAW_PART_KNOB", be_cconst_int(LV_ARC_DRAW_PART_KNOB) },
    { "ARC_MODE_NORMAL", be_cconst_int(LV_ARC_MODE_NORMAL) },
    { "ARC_MODE_REVERSE", be_cconst_int(LV_ARC_MODE_REVERSE) },
    { "ARC_MODE_SYMMETRICAL", be_cconst_int(LV_ARC_MODE_SYMMETRICAL) },
    { "BAR_DRAW_PART_INDICATOR", be_cconst_int(LV_BAR_DRAW_PART_INDICATOR) },
    { "BAR_MODE_NORMAL", be_cconst_int(LV_BAR_MODE_NORMAL) },
    { "BAR_MODE_RANGE", be_cconst_int(LV_BAR_MODE_RANGE) },
    { "BAR_MODE_SYMMETRICAL", be_cconst_int(LV_BAR_MODE_SYMMETRICAL) },
    { "BASE_DIR_AUTO", be_cconst_int(LV_BASE_DIR_AUTO) },
    { "BASE_DIR_LTR", be_cconst_int(LV_BASE_DIR_LTR) },
    { "BASE_DIR_NEUTRAL", be_cconst_int(LV_BASE_DIR_NEUTRAL) },
    { "BASE_DIR_RTL", be_cconst_int(LV_BASE_DIR_RTL) },
    { "BASE_DIR_WEAK", be_cconst_int(LV_BASE_DIR_WEAK) },
    { "BLEND_MODE_ADDITIVE", be_cconst_int(LV_BLEND_MODE_ADDITIVE) },
    { "BLEND_MODE_MULTIPLY", be_cconst_int(LV_BLEND_MODE_MULTIPLY) },
    { "BLEND_MODE_NORMAL", be_cconst_int(LV_BLEND_MODE_NORMAL) },
    { "BLEND_MODE_REPLACE", be_cconst_int(LV_BLEND_MODE_REPLACE) },
    { "BLEND_MODE_SUBTRACTIVE", be_cconst_int(LV_BLEND_MODE_SUBTRACTIVE) },
    { "BORDER_SIDE_BOTTOM", be_cconst_int(LV_BORDER_SIDE_BOTTOM) },
    { "BORDER_SIDE_FULL", be_cconst_int(LV_BORDER_SIDE_FULL) },
    { "BORDER_SIDE_INTERNAL", be_cconst_int(LV_BORDER_SIDE_INTERNAL) },
    { "BORDER_SIDE_LEFT", be_cconst_int(LV_BORDER_SIDE_LEFT) },
    { "BORDER_SIDE_NONE", be_cconst_int(LV_BORDER_SIDE_NONE) },
    { "BORDER_SIDE_RIGHT", be_cconst_int(LV_BORDER_SIDE_RIGHT) },
    { "BORDER_SIDE_TOP", be_cconst_int(LV_BORDER_SIDE_TOP) },
    { "BTNMATRIX_BTN_NONE", be_cconst_int(LV_BTNMATRIX_BTN_NONE) },
    { "BTNMATRIX_CTRL_CHECKABLE", be_cconst_int(LV_BTNMATRIX_CTRL_CHECKABLE) },
    { "BTNMATRIX_CTRL_CHECKED", be_cconst_int(LV_BTNMATRIX_CTRL_CHECKED) },
    { "BTNMATRIX_CTRL_CLICK_TRIG", be_cconst_int(LV_BTNMATRIX_CTRL_CLICK_TRIG) },
    { "BTNMATRIX_CTRL_CUSTOM_1", be_cconst_int(LV_BTNMATRIX_CTRL_CUSTOM_1) },
    { "BTNMATRIX_CTRL_CUSTOM_2", be_cconst_int(LV_BTNMATRIX_CTRL_CUSTOM_2) },
    { "BTNMATRIX_CTRL_DISABLED", be_cconst_int(LV_BTNMATRIX_CTRL_DISABLED) },
    { "BTNMATRIX_CTRL_HIDDEN", be_cconst_int(LV_BTNMATRIX_CTRL_HIDDEN) },
    { "BTNMATRIX_CTRL_NO_REPEAT", be_cconst_int(LV_BTNMATRIX_CTRL_NO_REPEAT) },
    { "BTNMATRIX_CTRL_POPOVER", be_cconst_int(LV_BTNMATRIX_CTRL_POPOVER) },
    { "BTNMATRIX_CTRL_RECOLOR", be_cconst_int(LV_BTNMATRIX_CTRL_RECOLOR) },
    { "BTNMATRIX_DRAW_PART_BTN", be_cconst_int(LV_BTNMATRIX_DRAW_PART_BTN) },
    { "CHART_AXIS_PRIMARY_X", be_cconst_int(LV_CHART_AXIS_PRIMARY_X) },
    { "CHART_AXIS_PRIMARY_Y", be_cconst_int(LV_CHART_AXIS_PRIMARY_Y) },
    { "CHART_AXIS_SECONDARY_X", be_cconst_int(LV_CHART_AXIS_SECONDARY_X) },
    { "CHART_AXIS_SECONDARY_Y", be_cconst_int(LV_CHART_AXIS_SECONDARY_Y) },
    { "CHART_DRAW_PART_BAR", be_cconst_int(LV_CHART_DRAW_PART_BAR) },
    { "CHART_DRAW_PART_CURSOR", be_cconst_int(LV_CHART_DRAW_PART_CURSOR) },
    { "CHART_DRAW_PART_DIV_LINE_HOR", be_cconst_int(LV_CHART_DRAW_PART_DIV_LINE_HOR) },
    { "CHART_DRAW_PART_DIV_LINE_INIT", be_cconst_int(LV_CHART_DRAW_PART_DIV_LINE_INIT) },
    { "CHART_DRAW_PART_DIV_LINE_VER", be_cconst_int(LV_CHART_DRAW_PART_DIV_LINE_VER) },
    { "CHART_DRAW_PART_LINE_AND_POINT", be_cconst_int(LV_CHART_DRAW_PART_LINE_AND_POINT) },
    { "CHART_DRAW_PART_TICK_LABEL", be_cconst_int(LV_CHART_DRAW_PART_TICK_LABEL) },
    { "CHART_POINT_NONE", be_cconst_int(LV_CHART_POINT_NONE) },
    { "CHART_TYPE_BAR", be_cconst_int(LV_CHART_TYPE_BAR) },
    { "CHART_TYPE_LINE", be_cconst_int(LV_CHART_TYPE_LINE) },
    { "CHART_TYPE_NONE", be_cconst_int(LV_CHART_TYPE_NONE) },
    { "CHART_TYPE_SCATTER", be_cconst_int(LV_CHART_TYPE_SCATTER) },
    { "CHART_UPDATE_MODE_CIRCULAR", be_cconst_int(LV_CHART_UPDATE_MODE_CIRCULAR) },
    { "CHART_UPDATE_MODE_SHIFT", be_cconst_int(LV_CHART_UPDATE_MODE_SHIFT) },
    { "CHECKBOX_DRAW_PART_BOX", be_cconst_int(LV_CHECKBOX_DRAW_PART_BOX) },
    { "COLORWHEEL_MODE_HUE", be_cconst_int(LV_COLORWHEEL_MODE_HUE) },
    { "COLORWHEEL_MODE_SATURATION", be_cconst_int(LV_COLORWHEEL_MODE_SATURATION) },
    { "COLORWHEEL_MODE_VALUE", be_cconst_int(LV_COLORWHEEL_MODE_VALUE) },
    { "COLOR_16_SWAP", be_cconst_int(LV_COLOR_16_SWAP) },
    { "COLOR_AQUA", be_cconst_int(0x00FFFF) },
    { "COLOR_BLACK", be_cconst_int(0x000000) },
    { "COLOR_BLUE", be_cconst_int(0x0000FF) },
    { "COLOR_CYAN", be_cconst_int(0x00FFFF) },
    { "COLOR_DEPTH", be_cconst_int(LV_COLOR_DEPTH) },
    { "COLOR_GRAY", be_cconst_int(0x808080) },
    { "COLOR_GREEN", be_cconst_int(0x008000) },
    { "COLOR_LIME", be_cconst_int(0x00FF00) },
    { "COLOR_MAGENTA", be_cconst_int(0xFF00FF) },
    { "COLOR_MAROON", be_cconst_int(0x800000) },
    { "COLOR_NAVY", be_cconst_int(0x000080) },
    { "COLOR_OLIVE", be_cconst_int(0x808000) },
    { "COLOR_ORANGE", be_cconst_int(0xFF7F00) },
    { "COLOR_PURPLE", be_cconst_int(0x800080) },
    { "COLOR_RED", be_cconst_int(0xFF0000) },
    { "COLOR_SILVER", be_cconst_int(0xC0C0C0) },
    { "COLOR_TEAL", be_cconst_int(0x008080) },
    { "COLOR_WHITE", be_cconst_int(0xFFFFFF) },
    { "COLOR_YELLOW", be_cconst_int(0xFFFF00) },
    { "COORD_MAX", be_cconst_int(LV_COORD_MAX) },
    { "COORD_MIN", be_cconst_int(LV_COORD_MIN) },
    { "COVER_RES_COVER", be_cconst_int(LV_COVER_RES_COVER) },
    { "COVER_RES_MASKED", be_cconst_int(LV_COVER_RES_MASKED) },
    { "COVER_RES_NOT_COVER", be_cconst_int(LV_COVER_RES_NOT_COVER) },
    { "DIR_ALL", be_cconst_int(LV_DIR_ALL) },
    { "DIR_BOTTOM", be_cconst_int(LV_DIR_BOTTOM) },
    { "DIR_HOR", be_cconst_int(LV_DIR_HOR) },
    { "DIR_LEFT", be_cconst_int(LV_DIR_LEFT) },
    { "DIR_NONE", be_cconst_int(LV_DIR_NONE) },
    { "DIR_RIGHT", be_cconst_int(LV_DIR_RIGHT) },
    { "DIR_TOP", be_cconst_int(LV_DIR_TOP) },
    { "DIR_VER", be_cconst_int(LV_DIR_VER) },
    { "DISP_ROT_180", be_cconst_int(LV_DISP_ROT_180) },
    { "DISP_ROT_270", be_cconst_int(LV_DISP_ROT_270) },
    { "DISP_ROT_90", be_cconst_int(LV_DISP_ROT_90) },
    { "DISP_ROT_NONE", be_cconst_int(LV_DISP_ROT_NONE) },
    { "DITHER_ERR_DIFF", be_cconst_int(LV_DITHER_ERR_DIFF) },
    { "DITHER_NONE", be_cconst_int(LV_DITHER_NONE) },
    { "DITHER_ORDERED", be_cconst_int(LV_DITHER_ORDERED) },
    { "DRAW_LAYER_FLAG_CAN_SUBDIVIDE", be_cconst_int(LV_DRAW_LAYER_FLAG_CAN_SUBDIVIDE) },
    { "DRAW_LAYER_FLAG_HAS_ALPHA", be_cconst_int(LV_DRAW_LAYER_FLAG_HAS_ALPHA) },
    { "DRAW_LAYER_FLAG_NONE", be_cconst_int(LV_DRAW_LAYER_FLAG_NONE) },
    { "DRAW_MASK_LINE_SIDE_BOTTOM", be_cconst_int(LV_DRAW_MASK_LINE_SIDE_BOTTOM) },
    { "DRAW_MASK_LINE_SIDE_LEFT", be_cconst_int(LV_DRAW_MASK_LINE_SIDE_LEFT) },
    { "DRAW_MASK_LINE_SIDE_RIGHT", be_cconst_int(LV_DRAW_MASK_LINE_SIDE_RIGHT) },
    { "DRAW_MASK_LINE_SIDE_TOP", be_cconst_int(LV_DRAW_MASK_LINE_SIDE_TOP) },
    { "DRAW_MASK_RES_CHANGED", be_cconst_int(LV_DRAW_MASK_RES_CHANGED) },
    { "DRAW_MASK_RES_FULL_COVER", be_cconst_int(LV_DRAW_MASK_RES_FULL_COVER) },
    { "DRAW_MASK_RES_TRANSP", be_cconst_int(LV_DRAW_MASK_RES_TRANSP) },
    { "DRAW_MASK_RES_UNKNOWN", be_cconst_int(LV_DRAW_MASK_RES_UNKNOWN) },
    { "DRAW_MASK_TYPE_ANGLE", be_cconst_int(LV_DRAW_MASK_TYPE_ANGLE) },
    { "DRAW_MASK_TYPE_FADE", be_cconst_int(LV_DRAW_MASK_TYPE_FADE) },
    { "DRAW_MASK_TYPE_LINE", be_cconst_int(LV_DRAW_MASK_TYPE_LINE) },
    { "DRAW_MASK_TYPE_MAP", be_cconst_int(LV_DRAW_MASK_TYPE_MAP) },
    { "DRAW_MASK_TYPE_POLYGON", be_cconst_int(LV_DRAW_MASK_TYPE_POLYGON) },
    { "DRAW_MASK_TYPE_RADIUS", be_cconst_int(LV_DRAW_MASK_TYPE_RADIUS) },
    { "DROPDOWN_POS_LAST", be_cconst_int(LV_DROPDOWN_POS_LAST) },
    { "EVENT_ALL", be_cconst_int(LV_EVENT_ALL) },
    { "EVENT_CANCEL", be_cconst_int(LV_EVENT_CANCEL) },
    { "EVENT_CHILD_CHANGED", be_cconst_int(LV_EVENT_CHILD_CHANGED) },
    { "EVENT_CHILD_CREATED", be_cconst_int(LV_EVENT_CHILD_CREATED) },
    { "EVENT_CHILD_DELETED", be_cconst_int(LV_EVENT_CHILD_DELETED) },
    { "EVENT_CLICKED", be_cconst_int(LV_EVENT_CLICKED) },
    { "EVENT_COVER_CHECK", be_cconst_int(LV_EVENT_COVER_CHECK) },
    { "EVENT_DEFOCUSED", be_cconst_int(LV_EVENT_DEFOCUSED) },
    { "EVENT_DELETE", be_cconst_int(LV_EVENT_DELETE) },
    { "EVENT_DRAW_MAIN", be_cconst_int(LV_EVENT_DRAW_MAIN) },
    { "EVENT_DRAW_MAIN_BEGIN", be_cconst_int(LV_EVENT_DRAW_MAIN_BEGIN) },
    { "EVENT_DRAW_MAIN_END", be_cconst_int(LV_EVENT_DRAW_MAIN_END) },
    { "EVENT_DRAW_PART_BEGIN", be_cconst_int(LV_EVENT_DRAW_PART_BEGIN) },
    { "EVENT_DRAW_PART_END", be_cconst_int(LV_EVENT_DRAW_PART_END) },
    { "EVENT_DRAW_POST", be_cconst_int(LV_EVENT_DRAW_POST) },
    { "EVENT_DRAW_POST_BEGIN", be_cconst_int(LV_EVENT_DRAW_POST_BEGIN) },
    { "EVENT_DRAW_POST_END", be_cconst_int(LV_EVENT_DRAW_POST_END) },
    { "EVENT_FOCUSED", be_cconst_int(LV_EVENT_FOCUSED) },
    { "EVENT_GESTURE", be_cconst_int(LV_EVENT_GESTURE) },
    { "EVENT_GET_SELF_SIZE", be_cconst_int(LV_EVENT_GET_SELF_SIZE) },
    { "EVENT_HIT_TEST", be_cconst_int(LV_EVENT_HIT_TEST) },
    { "EVENT_INSERT", be_cconst_int(LV_EVENT_INSERT) },
    { "EVENT_KEY", be_cconst_int(LV_EVENT_KEY) },
    { "EVENT_LAYOUT_CHANGED", be_cconst_int(LV_EVENT_LAYOUT_CHANGED) },
    { "EVENT_LEAVE", be_cconst_int(LV_EVENT_LEAVE) },
    { "EVENT_LONG_PRESSED", be_cconst_int(LV_EVENT_LONG_PRESSED) },
    { "EVENT_LONG_PRESSED_REPEAT", be_cconst_int(LV_EVENT_LONG_PRESSED_REPEAT) },
    { "EVENT_PREPROCESS", be_cconst_int(LV_EVENT_PREPROCESS) },
    { "EVENT_PRESSED", be_cconst_int(LV_EVENT_PRESSED) },
    { "EVENT_PRESSING", be_cconst_int(LV_EVENT_PRESSING) },
    { "EVENT_PRESS_LOST", be_cconst_int(LV_EVENT_PRESS_LOST) },
    { "EVENT_READY", be_cconst_int(LV_EVENT_READY) },
    { "EVENT_REFRESH", be_cconst_int(LV_EVENT_REFRESH) },
    { "EVENT_REFR_EXT_DRAW_SIZE", be_cconst_int(LV_EVENT_REFR_EXT_DRAW_SIZE) },
    { "EVENT_RELEASED", be_cconst_int(LV_EVENT_RELEASED) },
    { "EVENT_SCREEN_LOADED", be_cconst_int(LV_EVENT_SCREEN_LOADED) },
    { "EVENT_SCREEN_LOAD_START", be_cconst_int(LV_EVENT_SCREEN_LOAD_START) },
    { "EVENT_SCREEN_UNLOADED", be_cconst_int(LV_EVENT_SCREEN_UNLOADED) },
    { "EVENT_SCREEN_UNLOAD_START", be_cconst_int(LV_EVENT_SCREEN_UNLOAD_START) },
    { "EVENT_SCROLL", be_cconst_int(LV_EVENT_SCROLL) },
    { "EVENT_SCROLL_BEGIN", be_cconst_int(LV_EVENT_SCROLL_BEGIN) },
    { "EVENT_SCROLL_END", be_cconst_int(LV_EVENT_SCROLL_END) },
    { "EVENT_SHORT_CLICKED", be_cconst_int(LV_EVENT_SHORT_CLICKED) },
    { "EVENT_SIZE_CHANGED", be_cconst_int(LV_EVENT_SIZE_CHANGED) },
    { "EVENT_STYLE_CHANGED", be_cconst_int(LV_EVENT_STYLE_CHANGED) },
    { "EVENT_VALUE_CHANGED", be_cconst_int(LV_EVENT_VALUE_CHANGED) },
    { "FLEX_ALIGN_CENTER", be_cconst_int(LV_FLEX_ALIGN_CENTER) },
    { "FLEX_ALIGN_END", be_cconst_int(LV_FLEX_ALIGN_END) },
    { "FLEX_ALIGN_SPACE_AROUND", be_cconst_int(LV_FLEX_ALIGN_SPACE_AROUND) },
    { "FLEX_ALIGN_SPACE_BETWEEN", be_cconst_int(LV_FLEX_ALIGN_SPACE_BETWEEN) },
    { "FLEX_ALIGN_SPACE_EVENLY", be_cconst_int(LV_FLEX_ALIGN_SPACE_EVENLY) },
    { "FLEX_ALIGN_START", be_cconst_int(LV_FLEX_ALIGN_START) },
    { "FLEX_FLOW_COLUMN", be_cconst_int(LV_FLEX_FLOW_COLUMN) },
    { "FLEX_FLOW_COLUMN_REVERSE", be_cconst_int(LV_FLEX_FLOW_COLUMN_REVERSE) },
    { "FLEX_FLOW_COLUMN_WRAP", be_cconst_int(LV_FLEX_FLOW_COLUMN_WRAP) },
    { "FLEX_FLOW_COLUMN_WRAP_REVERSE", be_cconst_int(LV_FLEX_FLOW_COLUMN_WRAP_REVERSE) },
    { "FLEX_FLOW_ROW", be_cconst_int(LV_FLEX_FLOW_ROW) },
    { "FLEX_FLOW_ROW_REVERSE", be_cconst_int(LV_FLEX_FLOW_ROW_REVERSE) },
    { "FLEX_FLOW_ROW_WRAP", be_cconst_int(LV_FLEX_FLOW_ROW_WRAP) },
    { "FLEX_FLOW_ROW_WRAP_REVERSE", be_cconst_int(LV_FLEX_FLOW_ROW_WRAP_REVERSE) },
    { "FS_MODE_RD", be_cconst_int(LV_FS_MODE_RD) },
    { "FS_MODE_WR", be_cconst_int(LV_FS_MODE_WR) },
    { "FS_RES_BUSY", be_cconst_int(LV_FS_RES_BUSY) },
    { "FS_RES_DENIED", be_cconst_int(LV_FS_RES_DENIED) },
    { "FS_RES_FS_ERR", be_cconst_int(LV_FS_RES_FS_ERR) },
    { "FS_RES_FULL", be_cconst_int(LV_FS_RES_FULL) },
    { "FS_RES_HW_ERR", be_cconst_int(LV_FS_RES_HW_ERR) },
    { "FS_RES_INV_PARAM", be_cconst_int(LV_FS_RES_INV_PARAM) },
    { "FS_RES_LOCKED", be_cconst_int(LV_FS_RES_LOCKED) },
    { "FS_RES_NOT_EX", be_cconst_int(LV_FS_RES_NOT_EX) },
    { "FS_RES_NOT_IMP", be_cconst_int(LV_FS_RES_NOT_IMP) },
    { "FS_RES_OK", be_cconst_int(LV_FS_RES_OK) },
    { "FS_RES_OUT_OF_MEM", be_cconst_int(LV_FS_RES_OUT_OF_MEM) },
    { "FS_RES_TOUT", be_cconst_int(LV_FS_RES_TOUT) },
    { "FS_RES_UNKNOWN", be_cconst_int(LV_FS_RES_UNKNOWN) },
    { "FS_SEEK_CUR", be_cconst_int(LV_FS_SEEK_CUR) },
    { "FS_SEEK_END", be_cconst_int(LV_FS_SEEK_END) },
    { "FS_SEEK_SET", be_cconst_int(LV_FS_SEEK_SET) },
    { "FT_FONT_STYLE_BOLD", be_cconst_int(FT_FONT_STYLE_BOLD) },
    { "FT_FONT_STYLE_ITALIC", be_cconst_int(FT_FONT_STYLE_ITALIC) },
    { "FT_FONT_STYLE_NORMAL", be_cconst_int(FT_FONT_STYLE_NORMAL) },
    { "GRAD_DIR_HOR", be_cconst_int(LV_GRAD_DIR_HOR) },
    { "GRAD_DIR_NONE", be_cconst_int(LV_GRAD_DIR_NONE) },
    { "GRAD_DIR_VER", be_cconst_int(LV_GRAD_DIR_VER) },
    { "GRID_ALIGN_CENTER", be_cconst_int(LV_GRID_ALIGN_CENTER) },
    { "GRID_ALIGN_END", be_cconst_int(LV_GRID_ALIGN_END) },
    { "GRID_ALIGN_SPACE_AROUND", be_cconst_int(LV_GRID_ALIGN_SPACE_AROUND) },
    { "GRID_ALIGN_SPACE_BETWEEN", be_cconst_int(LV_GRID_ALIGN_SPACE_BETWEEN) },
    { "GRID_ALIGN_SPACE_EVENLY", be_cconst_int(LV_GRID_ALIGN_SPACE_EVENLY) },
    { "GRID_ALIGN_START", be_cconst_int(LV_GRID_ALIGN_START) },
    { "GRID_ALIGN_STRETCH", be_cconst_int(LV_GRID_ALIGN_STRETCH) },
    { "GRID_CONTENT", be_cconst_int(LV_GRID_CONTENT) },
    { "GRID_FR", be_cconst_int(LV_GRID_FR(0)) },
    { "GRID_TEMPLATE_LAST", be_cconst_int(LV_GRID_TEMPLATE_LAST) },
    { "GROUP_REFOCUS_POLICY_NEXT", be_cconst_int(LV_GROUP_REFOCUS_POLICY_NEXT) },
    { "GROUP_REFOCUS_POLICY_PREV", be_cconst_int(LV_GROUP_REFOCUS_POLICY_PREV) },
    { "IMGBTN_STATE_CHECKED_DISABLED", be_cconst_int(LV_IMGBTN_STATE_CHECKED_DISABLED) },
    { "IMGBTN_STATE_CHECKED_PRESSED", be_cconst_int(LV_IMGBTN_STATE_CHECKED_PRESSED) },
    { "IMGBTN_STATE_CHECKED_RELEASED", be_cconst_int(LV_IMGBTN_STATE_CHECKED_RELEASED) },
    { "IMGBTN_STATE_DISABLED", be_cconst_int(LV_IMGBTN_STATE_DISABLED) },
    { "IMGBTN_STATE_PRESSED", be_cconst_int(LV_IMGBTN_STATE_PRESSED) },
    { "IMGBTN_STATE_RELEASED", be_cconst_int(LV_IMGBTN_STATE_RELEASED) },
    { "IMG_CF_ALPHA_1BIT", be_cconst_int(LV_IMG_CF_ALPHA_1BIT) },
    { "IMG_CF_ALPHA_2BIT", be_cconst_int(LV_IMG_CF_ALPHA_2BIT) },
    { "IMG_CF_ALPHA_4BIT", be_cconst_int(LV_IMG_CF_ALPHA_4BIT) },
    { "IMG_CF_ALPHA_8BIT", be_cconst_int(LV_IMG_CF_ALPHA_8BIT) },
    { "IMG_CF_INDEXED_1BIT", be_cconst_int(LV_IMG_CF_INDEXED_1BIT) },
    { "IMG_CF_INDEXED_2BIT", be_cconst_int(LV_IMG_CF_INDEXED_2BIT) },
    { "IMG_CF_INDEXED_4BIT", be_cconst_int(LV_IMG_CF_INDEXED_4BIT) },
    { "IMG_CF_INDEXED_8BIT", be_cconst_int(LV_IMG_CF_INDEXED_8BIT) },
    { "IMG_CF_RAW", be_cconst_int(LV_IMG_CF_RAW) },
    { "IMG_CF_RAW_ALPHA", be_cconst_int(LV_IMG_CF_RAW_ALPHA) },
    { "IMG_CF_RAW_CHROMA_KEYED", be_cconst_int(LV_IMG_CF_RAW_CHROMA_KEYED) },
    { "IMG_CF_RGB565", be_cconst_int(LV_IMG_CF_RGB565) },
    { "IMG_CF_RGB565A8", be_cconst_int(LV_IMG_CF_RGB565A8) },
    { "IMG_CF_RGB888", be_cconst_int(LV_IMG_CF_RGB888) },
    { "IMG_CF_RGBA5658", be_cconst_int(LV_IMG_CF_RGBA5658) },
    { "IMG_CF_RGBA8888", be_cconst_int(LV_IMG_CF_RGBA8888) },
    { "IMG_CF_RGBX8888", be_cconst_int(LV_IMG_CF_RGBX8888) },
    { "IMG_CF_TRUE_COLOR", be_cconst_int(LV_IMG_CF_TRUE_COLOR) },
    { "IMG_CF_TRUE_COLOR_ALPHA", be_cconst_int(LV_IMG_CF_TRUE_COLOR_ALPHA) },
    { "IMG_CF_TRUE_COLOR_CHROMA_KEYED", be_cconst_int(LV_IMG_CF_TRUE_COLOR_CHROMA_KEYED) },
    { "IMG_CF_UNKNOWN", be_cconst_int(LV_IMG_CF_UNKNOWN) },
    { "IMG_SIZE_MODE_REAL", be_cconst_int(LV_IMG_SIZE_MODE_REAL) },
    { "IMG_SIZE_MODE_VIRTUAL", be_cconst_int(LV_IMG_SIZE_MODE_VIRTUAL) },
    { "IMG_SRC_FILE", be_cconst_int(LV_IMG_SRC_FILE) },
    { "IMG_SRC_SYMBOL", be_cconst_int(LV_IMG_SRC_SYMBOL) },
    { "IMG_SRC_UNKNOWN", be_cconst_int(LV_IMG_SRC_UNKNOWN) },
    { "IMG_SRC_VARIABLE", be_cconst_int(LV_IMG_SRC_VARIABLE) },
    { "IMG_ZOOM_NONE", be_cconst_int(LV_IMG_ZOOM_NONE) },
    { "INDEV_STATE_PRESSED", be_cconst_int(LV_INDEV_STATE_PRESSED) },
    { "INDEV_STATE_RELEASED", be_cconst_int(LV_INDEV_STATE_RELEASED) },
    { "INDEV_TYPE_BUTTON", be_cconst_int(LV_INDEV_TYPE_BUTTON) },
    { "INDEV_TYPE_ENCODER", be_cconst_int(LV_INDEV_TYPE_ENCODER) },
    { "INDEV_TYPE_KEYPAD", be_cconst_int(LV_INDEV_TYPE_KEYPAD) },
    { "INDEV_TYPE_NONE", be_cconst_int(LV_INDEV_TYPE_NONE) },
    { "INDEV_TYPE_POINTER", be_cconst_int(LV_INDEV_TYPE_POINTER) },
    { "KEY_BACKSPACE", be_cconst_int(LV_KEY_BACKSPACE) },
    { "KEY_DEL", be_cconst_int(LV_KEY_DEL) },
    { "KEY_DOWN", be_cconst_int(LV_KEY_DOWN) },
    { "KEY_END", be_cconst_int(LV_KEY_END) },
    { "KEY_ENTER", be_cconst_int(LV_KEY_ENTER) },
    { "KEY_ESC", be_cconst_int(LV_KEY_ESC) },
    { "KEY_HOME", be_cconst_int(LV_KEY_HOME) },
    { "KEY_LEFT", be_cconst_int(LV_KEY_LEFT) },
    { "KEY_NEXT", be_cconst_int(LV_KEY_NEXT) },
    { "KEY_PREV", be_cconst_int(LV_KEY_PREV) },
    { "KEY_RIGHT", be_cconst_int(LV_KEY_RIGHT) },
    { "KEY_UP", be_cconst_int(LV_KEY_UP) },
    { "LABEL_DOT_NUM", be_cconst_int(LV_LABEL_DOT_NUM) },
    { "LABEL_LONG_CLIP", be_cconst_int(LV_LABEL_LONG_CLIP) },
    { "LABEL_LONG_DOT", be_cconst_int(LV_LABEL_LONG_DOT) },
    { "LABEL_LONG_SCROLL", be_cconst_int(LV_LABEL_LONG_SCROLL) },
    { "LABEL_LONG_SCROLL_CIRCULAR", be_cconst_int(LV_LABEL_LONG_SCROLL_CIRCULAR) },
    { "LABEL_LONG_WRAP", be_cconst_int(LV_LABEL_LONG_WRAP) },
    { "LABEL_POS_LAST", be_cconst_int(LV_LABEL_POS_LAST) },
    { "LABEL_TEXT_SELECTION_OFF", be_cconst_int(LV_LABEL_TEXT_SELECTION_OFF) },
    { "LAYER_TYPE_NONE", be_cconst_int(LV_LAYER_TYPE_NONE) },
    { "LAYER_TYPE_SIMPLE", be_cconst_int(LV_LAYER_TYPE_SIMPLE) },
    { "LAYER_TYPE_TRANSFORM", be_cconst_int(LV_LAYER_TYPE_TRANSFORM) },
    { ">LAYOUT_FLEX", be_ctype(be_LV_LAYOUT_FLEX) },
    { ">LAYOUT_GRID", be_ctype(be_LV_LAYOUT_GRID) },
    { "LED_DRAW_PART_RECTANGLE", be_cconst_int(LV_LED_DRAW_PART_RECTANGLE) },
    { "LOG_LEVEL_ERROR", be_cconst_int(LV_LOG_LEVEL_ERROR) },
    { "LOG_LEVEL_INFO", be_cconst_int(LV_LOG_LEVEL_INFO) },
    { "LOG_LEVEL_NONE", be_cconst_int(LV_LOG_LEVEL_NONE) },
    { "LOG_LEVEL_TRACE", be_cconst_int(LV_LOG_LEVEL_TRACE) },
    { "LOG_LEVEL_USER", be_cconst_int(LV_LOG_LEVEL_USER) },
    { "LOG_LEVEL_WARN", be_cconst_int(LV_LOG_LEVEL_WARN) },
    { "MENU_HEADER_BOTTOM_FIXED", be_cconst_int(LV_MENU_HEADER_BOTTOM_FIXED) },
    { "MENU_HEADER_TOP_FIXED", be_cconst_int(LV_MENU_HEADER_TOP_FIXED) },
    { "MENU_HEADER_TOP_UNFIXED", be_cconst_int(LV_MENU_HEADER_TOP_UNFIXED) },
    { "MENU_ROOT_BACK_BTN_DISABLED", be_cconst_int(LV_MENU_ROOT_BACK_BTN_DISABLED) },
    { "MENU_ROOT_BACK_BTN_ENABLED", be_cconst_int(LV_MENU_ROOT_BACK_BTN_ENABLED) },
    { "METER_DRAW_PART_ARC", be_cconst_int(LV_METER_DRAW_PART_ARC) },
    { "METER_DRAW_PART_NEEDLE_IMG", be_cconst_int(LV_METER_DRAW_PART_NEEDLE_IMG) },
    { "METER_DRAW_PART_NEEDLE_LINE", be_cconst_int(LV_METER_DRAW_PART_NEEDLE_LINE) },
    { "METER_DRAW_PART_TICK", be_cconst_int(LV_METER_DRAW_PART_TICK) },
    { "METER_INDICATOR_TYPE_ARC", be_cconst_int(LV_METER_INDICATOR_TYPE_ARC) },
    { "METER_INDICATOR_TYPE_NEEDLE_IMG", be_cconst_int(LV_METER_INDICATOR_TYPE_NEEDLE_IMG) },
    { "METER_INDICATOR_TYPE_NEEDLE_LINE", be_cconst_int(LV_METER_INDICATOR_TYPE_NEEDLE_LINE) },
    { "METER_INDICATOR_TYPE_SCALE_LINES", be_cconst_int(LV_METER_INDICATOR_TYPE_SCALE_LINES) },
    { "OBJ_CLASS_EDITABLE_FALSE", be_cconst_int(LV_OBJ_CLASS_EDITABLE_FALSE) },
    { "OBJ_CLASS_EDITABLE_INHERIT", be_cconst_int(LV_OBJ_CLASS_EDITABLE_INHERIT) },
    { "OBJ_CLASS_EDITABLE_TRUE", be_cconst_int(LV_OBJ_CLASS_EDITABLE_TRUE) },
    { "OBJ_CLASS_GROUP_DEF_FALSE", be_cconst_int(LV_OBJ_CLASS_GROUP_DEF_FALSE) },
    { "OBJ_CLASS_GROUP_DEF_INHERIT", be_cconst_int(LV_OBJ_CLASS_GROUP_DEF_INHERIT) },
    { "OBJ_CLASS_GROUP_DEF_TRUE", be_cconst_int(LV_OBJ_CLASS_GROUP_DEF_TRUE) },
    { "OBJ_DRAW_PART_BORDER_POST", be_cconst_int(LV_OBJ_DRAW_PART_BORDER_POST) },
    { "OBJ_DRAW_PART_RECTANGLE", be_cconst_int(LV_OBJ_DRAW_PART_RECTANGLE) },
    { "OBJ_DRAW_PART_SCROLLBAR", be_cconst_int(LV_OBJ_DRAW_PART_SCROLLBAR) },
    { "OBJ_FLAG_ADV_HITTEST", be_cconst_int(LV_OBJ_FLAG_ADV_HITTEST) },
    { "OBJ_FLAG_CHECKABLE", be_cconst_int(LV_OBJ_FLAG_CHECKABLE) },
    { "OBJ_FLAG_CLICKABLE", be_cconst_int(LV_OBJ_FLAG_CLICKABLE) },
    { "OBJ_FLAG_CLICK_FOCUSABLE", be_cconst_int(LV_OBJ_FLAG_CLICK_FOCUSABLE) },
    { "OBJ_FLAG_EVENT_BUBBLE", be_cconst_int(LV_OBJ_FLAG_EVENT_BUBBLE) },
    { "OBJ_FLAG_FLEX_IN_NEW_TRACK", be_cconst_int(LV_OBJ_FLAG_FLEX_IN_NEW_TRACK) },
    { "OBJ_FLAG_FLOATING", be_cconst_int(LV_OBJ_FLAG_FLOATING) },
    { "OBJ_FLAG_GESTURE_BUBBLE", be_cconst_int(LV_OBJ_FLAG_GESTURE_BUBBLE) },
    { "OBJ_FLAG_HIDDEN", be_cconst_int(LV_OBJ_FLAG_HIDDEN) },
    { "OBJ_FLAG_IGNORE_LAYOUT", be_cconst_int(LV_OBJ_FLAG_IGNORE_LAYOUT) },
    { "OBJ_FLAG_LAYOUT_1", be_cconst_int(LV_OBJ_FLAG_LAYOUT_1) },
    { "OBJ_FLAG_LAYOUT_2", be_cconst_int(LV_OBJ_FLAG_LAYOUT_2) },
    { "OBJ_FLAG_OVERFLOW_VISIBLE", be_cconst_int(LV_OBJ_FLAG_OVERFLOW_VISIBLE) },
    { "OBJ_FLAG_PRESS_LOCK", be_cconst_int(LV_OBJ_FLAG_PRESS_LOCK) },
    { "OBJ_FLAG_SCROLLABLE", be_cconst_int(LV_OBJ_FLAG_SCROLLABLE) },
    { "OBJ_FLAG_SCROLL_CHAIN", be_cconst_int(LV_OBJ_FLAG_SCROLL_CHAIN) },
    { "OBJ_FLAG_SCROLL_CHAIN_HOR", be_cconst_int(LV_OBJ_FLAG_SCROLL_CHAIN_HOR) },
    { "OBJ_FLAG_SCROLL_CHAIN_VER", be_cconst_int(LV_OBJ_FLAG_SCROLL_CHAIN_VER) },
    { "OBJ_FLAG_SCROLL_ELASTIC", be_cconst_int(LV_OBJ_FLAG_SCROLL_ELASTIC) },
    { "OBJ_FLAG_SCROLL_MOMENTUM", be_cconst_int(LV_OBJ_FLAG_SCROLL_MOMENTUM) },
    { "OBJ_FLAG_SCROLL_ONE", be_cconst_int(LV_OBJ_FLAG_SCROLL_ONE) },
    { "OBJ_FLAG_SCROLL_ON_FOCUS", be_cconst_int(LV_OBJ_FLAG_SCROLL_ON_FOCUS) },
    { "OBJ_FLAG_SCROLL_WITH_ARROW", be_cconst_int(LV_OBJ_FLAG_SCROLL_WITH_ARROW) },
    { "OBJ_FLAG_SNAPPABLE", be_cconst_int(LV_OBJ_FLAG_SNAPPABLE) },
    { "OBJ_FLAG_USER_1", be_cconst_int(LV_OBJ_FLAG_USER_1) },
    { "OBJ_FLAG_USER_2", be_cconst_int(LV_OBJ_FLAG_USER_2) },
    { "OBJ_FLAG_USER_3", be_cconst_int(LV_OBJ_FLAG_USER_3) },
    { "OBJ_FLAG_USER_4", be_cconst_int(LV_OBJ_FLAG_USER_4) },
    { "OBJ_FLAG_WIDGET_1", be_cconst_int(LV_OBJ_FLAG_WIDGET_1) },
    { "OBJ_FLAG_WIDGET_2", be_cconst_int(LV_OBJ_FLAG_WIDGET_2) },
    { "OBJ_TREE_WALK_END", be_cconst_int(LV_OBJ_TREE_WALK_END) },
    { "OBJ_TREE_WALK_NEXT", be_cconst_int(LV_OBJ_TREE_WALK_NEXT) },
    { "OBJ_TREE_WALK_SKIP_CHILDREN", be_cconst_int(LV_OBJ_TREE_WALK_SKIP_CHILDREN) },
    { "OPA_0", be_cconst_int(LV_OPA_0) },
    { "OPA_10", be_cconst_int(LV_OPA_10) },
    { "OPA_100", be_cconst_int(LV_OPA_100) },
    { "OPA_20", be_cconst_int(LV_OPA_20) },
    { "OPA_30", be_cconst_int(LV_OPA_30) },
    { "OPA_40", be_cconst_int(LV_OPA_40) },
    { "OPA_50", be_cconst_int(LV_OPA_50) },
    { "OPA_60", be_cconst_int(LV_OPA_60) },
    { "OPA_70", be_cconst_int(LV_OPA_70) },
    { "OPA_80", be_cconst_int(LV_OPA_80) },
    { "OPA_90", be_cconst_int(LV_OPA_90) },
    { "OPA_COVER", be_cconst_int(LV_OPA_COVER) },
    { "OPA_TRANSP", be_cconst_int(LV_OPA_TRANSP) },
    { "PALETTE_AMBER", be_cconst_int(LV_PALETTE_AMBER) },
    { "PALETTE_BLUE", be_cconst_int(LV_PALETTE_BLUE) },
    { "PALETTE_BLUE_GREY", be_cconst_int(LV_PALETTE_BLUE_GREY) },
    { "PALETTE_BROWN", be_cconst_int(LV_PALETTE_BROWN) },
    { "PALETTE_CYAN", be_cconst_int(LV_PALETTE_CYAN) },
    { "PALETTE_DEEP_ORANGE", be_cconst_int(LV_PALETTE_DEEP_ORANGE) },
    { "PALETTE_DEEP_PURPLE", be_cconst_int(LV_PALETTE_DEEP_PURPLE) },
    { "PALETTE_GREEN", be_cconst_int(LV_PALETTE_GREEN) },
    { "PALETTE_GREY", be_cconst_int(LV_PALETTE_GREY) },
    { "PALETTE_INDIGO", be_cconst_int(LV_PALETTE_INDIGO) },
    { "PALETTE_LIGHT_BLUE", be_cconst_int(LV_PALETTE_LIGHT_BLUE) },
    { "PALETTE_LIGHT_GREEN", be_cconst_int(LV_PALETTE_LIGHT_GREEN) },
    { "PALETTE_LIME", be_cconst_int(LV_PALETTE_LIME) },
    { "PALETTE_NONE", be_cconst_int(LV_PALETTE_NONE) },
    { "PALETTE_ORANGE", be_cconst_int(LV_PALETTE_ORANGE) },
    { "PALETTE_PINK", be_cconst_int(LV_PALETTE_PINK) },
    { "PALETTE_PURPLE", be_cconst_int(LV_PALETTE_PURPLE) },
    { "PALETTE_RED", be_cconst_int(LV_PALETTE_RED) },
    { "PALETTE_TEAL", be_cconst_int(LV_PALETTE_TEAL) },
    { "PALETTE_YELLOW", be_cconst_int(LV_PALETTE_YELLOW) },
    { "PART_ANY", be_cconst_int(LV_PART_ANY) },
    { "PART_CURSOR", be_cconst_int(LV_PART_CURSOR) },
    { "PART_CUSTOM_FIRST", be_cconst_int(LV_PART_CUSTOM_FIRST) },
    { "PART_INDICATOR", be_cconst_int(LV_PART_INDICATOR) },
    { "PART_ITEMS", be_cconst_int(LV_PART_ITEMS) },
    { "PART_KNOB", be_cconst_int(LV_PART_KNOB) },
    { "PART_MAIN", be_cconst_int(LV_PART_MAIN) },
    { "PART_SCROLLBAR", be_cconst_int(LV_PART_SCROLLBAR) },
    { "PART_SELECTED", be_cconst_int(LV_PART_SELECTED) },
    { "PART_TEXTAREA_PLACEHOLDER", be_cconst_int(LV_PART_TEXTAREA_PLACEHOLDER) },
    { "PART_TICKS", be_cconst_int(LV_PART_TICKS) },
    { "RADIUS_CIRCLE", be_cconst_int(LV_RADIUS_CIRCLE) },
    { "RES_INV", be_cconst_int(LV_RES_INV) },
    { "RES_OK", be_cconst_int(LV_RES_OK) },
    { "ROLLER_MODE_INFINITE", be_cconst_int(LV_ROLLER_MODE_INFINITE) },
    { "ROLLER_MODE_NORMAL", be_cconst_int(LV_ROLLER_MODE_NORMAL) },
    { "SCROLLBAR_MODE_ACTIVE", be_cconst_int(LV_SCROLLBAR_MODE_ACTIVE) },
    { "SCROLLBAR_MODE_AUTO", be_cconst_int(LV_SCROLLBAR_MODE_AUTO) },
    { "SCROLLBAR_MODE_OFF", be_cconst_int(LV_SCROLLBAR_MODE_OFF) },
    { "SCROLLBAR_MODE_ON", be_cconst_int(LV_SCROLLBAR_MODE_ON) },
    { "SCROLL_SNAP_CENTER", be_cconst_int(LV_SCROLL_SNAP_CENTER) },
    { "SCROLL_SNAP_END", be_cconst_int(LV_SCROLL_SNAP_END) },
    { "SCROLL_SNAP_NONE", be_cconst_int(LV_SCROLL_SNAP_NONE) },
    { "SCROLL_SNAP_START", be_cconst_int(LV_SCROLL_SNAP_START) },
    { "SCR_LOAD_ANIM_FADE_IN", be_cconst_int(LV_SCR_LOAD_ANIM_FADE_IN) },
    { "SCR_LOAD_ANIM_FADE_ON", be_cconst_int(LV_SCR_LOAD_ANIM_FADE_ON) },
    { "SCR_LOAD_ANIM_FADE_OUT", be_cconst_int(LV_SCR_LOAD_ANIM_FADE_OUT) },
    { "SCR_LOAD_ANIM_MOVE_BOTTOM", be_cconst_int(LV_SCR_LOAD_ANIM_MOVE_BOTTOM) },
    { "SCR_LOAD_ANIM_MOVE_LEFT", be_cconst_int(LV_SCR_LOAD_ANIM_MOVE_LEFT) },
    { "SCR_LOAD_ANIM_MOVE_RIGHT", be_cconst_int(LV_SCR_LOAD_ANIM_MOVE_RIGHT) },
    { "SCR_LOAD_ANIM_MOVE_TOP", be_cconst_int(LV_SCR_LOAD_ANIM_MOVE_TOP) },
    { "SCR_LOAD_ANIM_NONE", be_cconst_int(LV_SCR_LOAD_ANIM_NONE) },
    { "SCR_LOAD_ANIM_OUT_BOTTOM", be_cconst_int(LV_SCR_LOAD_ANIM_OUT_BOTTOM) },
    { "SCR_LOAD_ANIM_OUT_LEFT", be_cconst_int(LV_SCR_LOAD_ANIM_OUT_LEFT) },
    { "SCR_LOAD_ANIM_OUT_RIGHT", be_cconst_int(LV_SCR_LOAD_ANIM_OUT_RIGHT) },
    { "SCR_LOAD_ANIM_OUT_TOP", be_cconst_int(LV_SCR_LOAD_ANIM_OUT_TOP) },
    { "SCR_LOAD_ANIM_OVER_BOTTOM", be_cconst_int(LV_SCR_LOAD_ANIM_OVER_BOTTOM) },
    { "SCR_LOAD_ANIM_OVER_LEFT", be_cconst_int(LV_SCR_LOAD_ANIM_OVER_LEFT) },
    { "SCR_LOAD_ANIM_OVER_RIGHT", be_cconst_int(LV_SCR_LOAD_ANIM_OVER_RIGHT) },
    { "SCR_LOAD_ANIM_OVER_TOP", be_cconst_int(LV_SCR_LOAD_ANIM_OVER_TOP) },
    { "SIZE_CONTENT", be_cconst_int(LV_SIZE_CONTENT) },
    { "SLIDER_DRAW_PART_KNOB", be_cconst_int(LV_SLIDER_DRAW_PART_KNOB) },
    { "SLIDER_DRAW_PART_KNOB_LEFT", be_cconst_int(LV_SLIDER_DRAW_PART_KNOB_LEFT) },
    { "SLIDER_MODE_NORMAL", be_cconst_int(LV_SLIDER_MODE_NORMAL) },
    { "SLIDER_MODE_RANGE", be_cconst_int(LV_SLIDER_MODE_RANGE) },
    { "SLIDER_MODE_SYMMETRICAL", be_cconst_int(LV_SLIDER_MODE_SYMMETRICAL) },
    { "SPAN_MODE_BREAK", be_cconst_int(LV_SPAN_MODE_BREAK) },
    { "SPAN_MODE_EXPAND", be_cconst_int(LV_SPAN_MODE_EXPAND) },
    { "SPAN_MODE_FIXED", be_cconst_int(LV_SPAN_MODE_FIXED) },
    { "SPAN_OVERFLOW_CLIP", be_cconst_int(LV_SPAN_OVERFLOW_CLIP) },
    { "SPAN_OVERFLOW_ELLIPSIS", be_cconst_int(LV_SPAN_OVERFLOW_ELLIPSIS) },
    { "STATE_ANY", be_cconst_int(LV_STATE_ANY) },
    { "STATE_CHECKED", be_cconst_int(LV_STATE_CHECKED) },
    { "STATE_DEFAULT", be_cconst_int(LV_STATE_DEFAULT) },
    { "STATE_DISABLED", be_cconst_int(LV_STATE_DISABLED) },
    { "STATE_EDITED", be_cconst_int(LV_STATE_EDITED) },
    { "STATE_FOCUSED", be_cconst_int(LV_STATE_FOCUSED) },
    { "STATE_FOCUS_KEY", be_cconst_int(LV_STATE_FOCUS_KEY) },
    { "STATE_HOVERED", be_cconst_int(LV_STATE_HOVERED) },
    { "STATE_PRESSED", be_cconst_int(LV_STATE_PRESSED) },
    { "STATE_SCROLLED", be_cconst_int(LV_STATE_SCROLLED) },
    { "STATE_USER_1", be_cconst_int(LV_STATE_USER_1) },
    { "STATE_USER_2", be_cconst_int(LV_STATE_USER_2) },
    { "STATE_USER_3", be_cconst_int(LV_STATE_USER_3) },
    { "STATE_USER_4", be_cconst_int(LV_STATE_USER_4) },
    { "STYLE_ALIGN", be_cconst_int(LV_STYLE_ALIGN) },
    { "STYLE_ANIM", be_cconst_int(LV_STYLE_ANIM) },
    { "STYLE_ANIM_SPEED", be_cconst_int(LV_STYLE_ANIM_SPEED) },
    { "STYLE_ANIM_TIME", be_cconst_int(LV_STYLE_ANIM_TIME) },
    { "STYLE_ARC_COLOR", be_cconst_int(LV_STYLE_ARC_COLOR) },
    { "STYLE_ARC_IMG_SRC", be_cconst_int(LV_STYLE_ARC_IMG_SRC) },
    { "STYLE_ARC_OPA", be_cconst_int(LV_STYLE_ARC_OPA) },
    { "STYLE_ARC_ROUNDED", be_cconst_int(LV_STYLE_ARC_ROUNDED) },
    { "STYLE_ARC_WIDTH", be_cconst_int(LV_STYLE_ARC_WIDTH) },
    { "STYLE_BASE_DIR", be_cconst_int(LV_STYLE_BASE_DIR) },
    { "STYLE_BG_COLOR", be_cconst_int(LV_STYLE_BG_COLOR) },
    { "STYLE_BG_DITHER_MODE", be_cconst_int(LV_STYLE_BG_DITHER_MODE) },
    { "STYLE_BG_GRAD", be_cconst_int(LV_STYLE_BG_GRAD) },
    { "STYLE_BG_GRAD_COLOR", be_cconst_int(LV_STYLE_BG_GRAD_COLOR) },
    { "STYLE_BG_GRAD_DIR", be_cconst_int(LV_STYLE_BG_GRAD_DIR) },
    { "STYLE_BG_GRAD_STOP", be_cconst_int(LV_STYLE_BG_GRAD_STOP) },
    { "STYLE_BG_IMG_OPA", be_cconst_int(LV_STYLE_BG_IMG_OPA) },
    { "STYLE_BG_IMG_RECOLOR", be_cconst_int(LV_STYLE_BG_IMG_RECOLOR) },
    { "STYLE_BG_IMG_RECOLOR_OPA", be_cconst_int(LV_STYLE_BG_IMG_RECOLOR_OPA) },
    { "STYLE_BG_IMG_SRC", be_cconst_int(LV_STYLE_BG_IMG_SRC) },
    { "STYLE_BG_IMG_TILED", be_cconst_int(LV_STYLE_BG_IMG_TILED) },
    { "STYLE_BG_MAIN_STOP", be_cconst_int(LV_STYLE_BG_MAIN_STOP) },
    { "STYLE_BG_OPA", be_cconst_int(LV_STYLE_BG_OPA) },
    { "STYLE_BLEND_MODE", be_cconst_int(LV_STYLE_BLEND_MODE) },
    { "STYLE_BORDER_COLOR", be_cconst_int(LV_STYLE_BORDER_COLOR) },
    { "STYLE_BORDER_OPA", be_cconst_int(LV_STYLE_BORDER_OPA) },
    { "STYLE_BORDER_POST", be_cconst_int(LV_STYLE_BORDER_POST) },
    { "STYLE_BORDER_SIDE", be_cconst_int(LV_STYLE_BORDER_SIDE) },
    { "STYLE_BORDER_WIDTH", be_cconst_int(LV_STYLE_BORDER_WIDTH) },
    { "STYLE_CLIP_CORNER", be_cconst_int(LV_STYLE_CLIP_CORNER) },
    { "STYLE_COLOR_FILTER_DSC", be_cconst_int(LV_STYLE_COLOR_FILTER_DSC) },
    { "STYLE_COLOR_FILTER_OPA", be_cconst_int(LV_STYLE_COLOR_FILTER_OPA) },
    { "STYLE_HEIGHT", be_cconst_int(LV_STYLE_HEIGHT) },
    { "STYLE_IMG_OPA", be_cconst_int(LV_STYLE_IMG_OPA) },
    { "STYLE_IMG_RECOLOR", be_cconst_int(LV_STYLE_IMG_RECOLOR) },
    { "STYLE_IMG_RECOLOR_OPA", be_cconst_int(LV_STYLE_IMG_RECOLOR_OPA) },
    { "STYLE_LAYOUT", be_cconst_int(LV_STYLE_LAYOUT) },
    { "STYLE_LINE_COLOR", be_cconst_int(LV_STYLE_LINE_COLOR) },
    { "STYLE_LINE_DASH_GAP", be_cconst_int(LV_STYLE_LINE_DASH_GAP) },
    { "STYLE_LINE_DASH_WIDTH", be_cconst_int(LV_STYLE_LINE_DASH_WIDTH) },
    { "STYLE_LINE_OPA", be_cconst_int(LV_STYLE_LINE_OPA) },
    { "STYLE_LINE_ROUNDED", be_cconst_int(LV_STYLE_LINE_ROUNDED) },
    { "STYLE_LINE_WIDTH", be_cconst_int(LV_STYLE_LINE_WIDTH) },
    { "STYLE_MAX_HEIGHT", be_cconst_int(LV_STYLE_MAX_HEIGHT) },
    { "STYLE_MAX_WIDTH", be_cconst_int(LV_STYLE_MAX_WIDTH) },
    { "STYLE_MIN_HEIGHT", be_cconst_int(LV_STYLE_MIN_HEIGHT) },
    { "STYLE_MIN_WIDTH", be_cconst_int(LV_STYLE_MIN_WIDTH) },
    { "STYLE_OPA", be_cconst_int(LV_STYLE_OPA) },
    { "STYLE_OPA_LAYERED", be_cconst_int(LV_STYLE_OPA_LAYERED) },
    { "STYLE_OUTLINE_COLOR", be_cconst_int(LV_STYLE_OUTLINE_COLOR) },
    { "STYLE_OUTLINE_OPA", be_cconst_int(LV_STYLE_OUTLINE_OPA) },
    { "STYLE_OUTLINE_PAD", be_cconst_int(LV_STYLE_OUTLINE_PAD) },
    { "STYLE_OUTLINE_WIDTH", be_cconst_int(LV_STYLE_OUTLINE_WIDTH) },
    { "STYLE_PAD_BOTTOM", be_cconst_int(LV_STYLE_PAD_BOTTOM) },
    { "STYLE_PAD_COLUMN", be_cconst_int(LV_STYLE_PAD_COLUMN) },
    { "STYLE_PAD_LEFT", be_cconst_int(LV_STYLE_PAD_LEFT) },
    { "STYLE_PAD_RIGHT", be_cconst_int(LV_STYLE_PAD_RIGHT) },
    { "STYLE_PAD_ROW", be_cconst_int(LV_STYLE_PAD_ROW) },
    { "STYLE_PAD_TOP", be_cconst_int(LV_STYLE_PAD_TOP) },
    { "STYLE_PROP_ANY", be_cconst_int(LV_STYLE_PROP_ANY) },
    { "STYLE_PROP_INV", be_cconst_int(LV_STYLE_PROP_INV) },
    { "STYLE_RADIUS", be_cconst_int(LV_STYLE_RADIUS) },
    { "STYLE_RES_FOUND", be_cconst_int(LV_STYLE_RES_FOUND) },
    { "STYLE_RES_INHERIT", be_cconst_int(LV_STYLE_RES_INHERIT) },
    { "STYLE_RES_NOT_FOUND", be_cconst_int(LV_STYLE_RES_NOT_FOUND) },
    { "STYLE_SHADOW_COLOR", be_cconst_int(LV_STYLE_SHADOW_COLOR) },
    { "STYLE_SHADOW_OFS_X", be_cconst_int(LV_STYLE_SHADOW_OFS_X) },
    { "STYLE_SHADOW_OFS_Y", be_cconst_int(LV_STYLE_SHADOW_OFS_Y) },
    { "STYLE_SHADOW_OPA", be_cconst_int(LV_STYLE_SHADOW_OPA) },
    { "STYLE_SHADOW_SPREAD", be_cconst_int(LV_STYLE_SHADOW_SPREAD) },
    { "STYLE_SHADOW_WIDTH", be_cconst_int(LV_STYLE_SHADOW_WIDTH) },
    { "STYLE_TEXT_ALIGN", be_cconst_int(LV_STYLE_TEXT_ALIGN) },
    { "STYLE_TEXT_COLOR", be_cconst_int(LV_STYLE_TEXT_COLOR) },
    { "STYLE_TEXT_DECOR", be_cconst_int(LV_STYLE_TEXT_DECOR) },
    { "STYLE_TEXT_FONT", be_cconst_int(LV_STYLE_TEXT_FONT) },
    { "STYLE_TEXT_LETTER_SPACE", be_cconst_int(LV_STYLE_TEXT_LETTER_SPACE) },
    { "STYLE_TEXT_LINE_SPACE", be_cconst_int(LV_STYLE_TEXT_LINE_SPACE) },
    { "STYLE_TEXT_OPA", be_cconst_int(LV_STYLE_TEXT_OPA) },
    { "STYLE_TRANSFORM_ANGLE", be_cconst_int(LV_STYLE_TRANSFORM_ANGLE) },
    { "STYLE_TRANSFORM_HEIGHT", be_cconst_int(LV_STYLE_TRANSFORM_HEIGHT) },
    { "STYLE_TRANSFORM_PIVOT_X", be_cconst_int(LV_STYLE_TRANSFORM_PIVOT_X) },
    { "STYLE_TRANSFORM_PIVOT_Y", be_cconst_int(LV_STYLE_TRANSFORM_PIVOT_Y) },
    { "STYLE_TRANSFORM_WIDTH", be_cconst_int(LV_STYLE_TRANSFORM_WIDTH) },
    { "STYLE_TRANSFORM_ZOOM", be_cconst_int(LV_STYLE_TRANSFORM_ZOOM) },
    { "STYLE_TRANSITION", be_cconst_int(LV_STYLE_TRANSITION) },
    { "STYLE_TRANSLATE_X", be_cconst_int(LV_STYLE_TRANSLATE_X) },
    { "STYLE_TRANSLATE_Y", be_cconst_int(LV_STYLE_TRANSLATE_Y) },
    { "STYLE_WIDTH", be_cconst_int(LV_STYLE_WIDTH) },
    { "STYLE_X", be_cconst_int(LV_STYLE_X) },
    { "STYLE_Y", be_cconst_int(LV_STYLE_Y) },
    { "$SYMBOL_AUDIO", be_cconst_string("\xef\x80\x81") },
    { "$SYMBOL_BACKSPACE", be_cconst_string("\xef\x95\x9A") },
    { "$SYMBOL_BATTERY_1", be_cconst_string("\xef\x89\x83") },
    { "$SYMBOL_BATTERY_2", be_cconst_string("\xef\x89\x82") },
    { "$SYMBOL_BATTERY_3", be_cconst_string("\xef\x89\x81") },
    { "$SYMBOL_BATTERY_EMPTY", be_cconst_string("\xef\x89\x84") },
    { "$SYMBOL_BATTERY_FULL", be_cconst_string("\xef\x89\x80") },
    { "$SYMBOL_BELL", be_cconst_string("\xef\x83\xb3") },
    { "$SYMBOL_BLUETOOTH", be_cconst_string("\xef\x8a\x93") },
    { "$SYMBOL_BULLET", be_cconst_string("\xE2\x80\xA2") },
    { "$SYMBOL_CALL", be_cconst_string("\xef\x82\x95") },
    { "$SYMBOL_CHARGE", be_cconst_string("\xef\x83\xa7") },
    { "$SYMBOL_CLOSE", be_cconst_string("\xef\x80\x8d") },
    { "$SYMBOL_COPY", be_cconst_string("\xef\x83\x85") },
    { "$SYMBOL_CUT", be_cconst_string("\xef\x83\x84") },
    { "$SYMBOL_DIRECTORY", be_cconst_string("\xef\x81\xbb") },
    { "$SYMBOL_DOWN", be_cconst_string("\xef\x81\xb8") },
    { "$SYMBOL_DOWNLOAD", be_cconst_string("\xef\x80\x99") },
    { "$SYMBOL_DRIVE", be_cconst_string("\xef\x80\x9c") },
    { "$SYMBOL_DUMMY", be_cconst_string("\xEF\xA3\xBF") },
    { "$SYMBOL_EDIT", be_cconst_string("\xef\x8C\x84") },
    { "$SYMBOL_EJECT", be_cconst_string("\xef\x81\x92") },
    { "$SYMBOL_EYE_CLOSE", be_cconst_string("\xef\x81\xb0") },
    { "$SYMBOL_EYE_OPEN", be_cconst_string("\xef\x81\xae") },
    { "$SYMBOL_FILE", be_cconst_string("\xef\x85\x9b") },
    { "$SYMBOL_GPS", be_cconst_string("\xef\x84\xa4") },
    { "$SYMBOL_HOME", be_cconst_string("\xef\x80\x95") },
    { "$SYMBOL_IMAGE", be_cconst_string("\xef\x80\xbe") },
    { "$SYMBOL_KEYBOARD", be_cconst_string("\xef\x84\x9c") },
    { "$SYMBOL_LEFT", be_cconst_string("\xef\x81\x93") },
    { "$SYMBOL_LIST", be_cconst_string("\xef\x80\x8b") },
    { "$SYMBOL_LOOP", be_cconst_string("\xef\x81\xb9") },
    { "$SYMBOL_MINUS", be_cconst_string("\xef\x81\xa8") },
    { "$SYMBOL_MUTE", be_cconst_string("\xef\x80\xa6") },
    { "$SYMBOL_NEW_LINE", be_cconst_string("\xef\xA2\xA2") },
    { "$SYMBOL_NEXT", be_cconst_string("\xef\x81\x91") },
    { "$SYMBOL_OK", be_cconst_string("\xef\x80\x8c") },
    { "$SYMBOL_PASTE", be_cconst_string("\xef\x83\xAA") },
    { "$SYMBOL_PAUSE", be_cconst_string("\xef\x81\x8c") },
    { "$SYMBOL_PLAY", be_cconst_string("\xef\x81\x8b") },
    { "$SYMBOL_PLUS", be_cconst_string("\xef\x81\xa7") },
    { "$SYMBOL_POWER", be_cconst_string("\xef\x80\x91") },
    { "$SYMBOL_PREV", be_cconst_string("\xef\x81\x88") },
    { "$SYMBOL_REFRESH", be_cconst_string("\xef\x80\xa1") },
    { "$SYMBOL_RIGHT", be_cconst_string("\xef\x81\x94") },
    { "$SYMBOL_SAVE", be_cconst_string("\xef\x83\x87") },
    { "$SYMBOL_SD_CARD", be_cconst_string("\xef\x9F\x82") },
    { "$SYMBOL_SETTINGS", be_cconst_string("\xef\x80\x93") },
    { "$SYMBOL_SHUFFLE", be_cconst_string("\xef\x81\xb4") },
    { "$SYMBOL_STOP", be_cconst_string("\xef\x81\x8d") },
    { "$SYMBOL_TRASH", be_cconst_string("\xef\x8B\xAD") },
    { "$SYMBOL_UP", be_cconst_string("\xef\x81\xb7") },
    { "$SYMBOL_UPLOAD", be_cconst_string("\xef\x82\x93") },
    { "$SYMBOL_USB", be_cconst_string("\xef\x8a\x87") },
    { "$SYMBOL_VIDEO", be_cconst_string("\xef\x80\x88") },
    { "$SYMBOL_VOLUME_MAX", be_cconst_string("\xef\x80\xa8") },
    { "$SYMBOL_VOLUME_MID", be_cconst_string("\xef\x80\xa7") },
    { "$SYMBOL_WARNING", be_cconst_string("\xef\x81\xb1") },
    { "$SYMBOL_WIFI", be_cconst_string("\xef\x87\xab") },
    { "TABLE_CELL_CTRL_CUSTOM_1", be_cconst_int(LV_TABLE_CELL_CTRL_CUSTOM_1) },
    { "TABLE_CELL_CTRL_CUSTOM_2", be_cconst_int(LV_TABLE_CELL_CTRL_CUSTOM_2) },
    { "TABLE_CELL_CTRL_CUSTOM_3", be_cconst_int(LV_TABLE_CELL_CTRL_CUSTOM_3) },
    { "TABLE_CELL_CTRL_CUSTOM_4", be_cconst_int(LV_TABLE_CELL_CTRL_CUSTOM_4) },
    { "TABLE_CELL_CTRL_MERGE_RIGHT", be_cconst_int(LV_TABLE_CELL_CTRL_MERGE_RIGHT) },
    { "TABLE_CELL_CTRL_TEXT_CROP", be_cconst_int(LV_TABLE_CELL_CTRL_TEXT_CROP) },
    { "TABLE_CELL_NONE", be_cconst_int(LV_TABLE_CELL_NONE) },
    { "TABLE_DRAW_PART_CELL", be_cconst_int(LV_TABLE_DRAW_PART_CELL) },
    { "TEXTAREA_CURSOR_LAST", be_cconst_int(LV_TEXTAREA_CURSOR_LAST) },
    { "TEXT_ALIGN_AUTO", be_cconst_int(LV_TEXT_ALIGN_AUTO) },
    { "TEXT_ALIGN_CENTER", be_cconst_int(LV_TEXT_ALIGN_CENTER) },
    { "TEXT_ALIGN_LEFT", be_cconst_int(LV_TEXT_ALIGN_LEFT) },
    { "TEXT_ALIGN_RIGHT", be_cconst_int(LV_TEXT_ALIGN_RIGHT) },
    { "TEXT_CMD_STATE_IN", be_cconst_int(LV_TEXT_CMD_STATE_IN) },
    { "TEXT_CMD_STATE_PAR", be_cconst_int(LV_TEXT_CMD_STATE_PAR) },
    { "TEXT_CMD_STATE_WAIT", be_cconst_int(LV_TEXT_CMD_STATE_WAIT) },
    { "TEXT_DECOR_NONE", be_cconst_int(LV_TEXT_DECOR_NONE) },
    { "TEXT_DECOR_STRIKETHROUGH", be_cconst_int(LV_TEXT_DECOR_STRIKETHROUGH) },
    { "TEXT_DECOR_UNDERLINE", be_cconst_int(LV_TEXT_DECOR_UNDERLINE) },
    { "TEXT_FLAG_EXPAND", be_cconst_int(LV_TEXT_FLAG_EXPAND) },
    { "TEXT_FLAG_FIT", be_cconst_int(LV_TEXT_FLAG_FIT) },
    { "TEXT_FLAG_NONE", be_cconst_int(LV_TEXT_FLAG_NONE) },
    { "TEXT_FLAG_RECOLOR", be_cconst_int(LV_TEXT_FLAG_RECOLOR) },
    { "&anim_path_bounce", be_cconst_ptr(&lv_anim_path_bounce) },
    { "&anim_path_ease_in", be_cconst_ptr(&lv_anim_path_ease_in) },
    { "&anim_path_ease_in_out", be_cconst_ptr(&lv_anim_path_ease_in_out) },
    { "&anim_path_ease_out", be_cconst_ptr(&lv_anim_path_ease_out) },
    { "&anim_path_linear", be_cconst_ptr(&lv_anim_path_linear) },
    { "&anim_path_overshoot", be_cconst_ptr(&lv_anim_path_overshoot) },
    { "&anim_path_step", be_cconst_ptr(&lv_anim_path_step) },
    { "@load_font", be_cconst_ptr(&lv0_load_font) },

};

const size_t lv0_constants_size = sizeof(lv0_constants)/sizeof(lv0_constants[0]);

#include "../src/solidify/solidified_lv.h"

/* @const_object_info_begin
module lv (scope: global, file: lv) {
    init, closure(lv_module_init_closure)
    member, func(lv0_member)
}
@const_object_info_end */
#include "be_fixed_lv.h"

/********************************************************************/
